### ISSUE TITLE
Names of French Revolutionary calendar months

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#103]
https://en.wikipedia.org/wiki/French_Republican_calendar#Months has:

> The French Republican calendar or French Revolutionary calendar are the names given to the new calendar adopted in 1794 by the French National Convention. This calendar was adopted on Gregorian day 22 September 1792, which was 1 Vendémiaire 1 in this calendar. It was abandoned 18 years later.
> 
> Permitted months are
> 
> |Code  |Name               |
> |:-----|:------------------|
> |`VEND`|Vendemiaire        |
> |`BRUM`|Brumaire           |
> |`FRIM`|Frimaire           |
> |`NIVO`|Nivose             |
> |`PLUV`|Pluviose           |
> |`VENT`|Ventose            |
> |`GERM`|Germinal           |
> |`FLOR`|Floreal            |
> |`PRAI`|Prairial           |
> |`MESS`|Messidor           |
> |`THER`|Thermidor          |
> |`FRUC`|Fructidor          |
> |`COMP`|Jour Complementairs|

The Name column above is missing diacritics.  For example, the text above the table uses Vendémiaire  which does not match the name in the table.

https://en.wikipedia.org/wiki/French_Republican_calendar#Months shows that 5 of the months should contain diacritics.

**Comment by elyoh** [comment]
`Jour Complementairs` is also missing a diacritic; should be `Jour complémentaires`.  PR submitted https://github.com/FamilySearch/GEDCOM/pull/120.
