### ISSUE TITLE
Nonsensical days in DateExact

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#113]
The spec currently has:
```
date        = [calendar D] [[day D] month D] year [D epoch]
day     = Integer
year    = Integer
month   = stdTag / extTag  ; constrained by calendar
```

Thus "2022 FEB 18" would be considered a legal date, being the 2022'nd day of February in the year 18 AD.   Is that intentionally legal?   To me this would seem better to not treat as legal or it will just encourage dates being entered in the wrong format (2022 FEB 18 instead of 18 FEB 2022).

Similarly "0 FEB 2022" is also currently a legal date it seems, which is also non-sensical.

Options:
1. No change.   "2022 FEB 18" and "0 FEB 2022" are both legal dates.
2. Constrain the day range independent of the calendar, such as to a value in the range [1,36] or even [1,366].
3. Constrain the day range based on a calendar-specific rule.

My preference would be to do 3 if the calendar is recognized, and 2 for unrecognized calendars.

**Comment by dthaler** [comment]
GEDCOM Steering Committee: general agreement to make some change for the DateExact.   Option 2 would be appropriate in all cases (James to find reasonable bounds).  Option 3 is ok to allow implementations to do if they recognize the calendar.

**Comment by tychonievich** [comment]
Discussed in re patch/minor/major. Decided that the admission of invalid dates was an oversight to be patched.

We plan to write up a patch that does something like

1. Ban invalid dates in any given calendar (without defining what that means)
2. State that "across known calendars, none of them use day 0 or have day greater than 36, and we expect others won't either" or the like

**Comment by elyoh** [comment]
> State that "across known calendars, none of them use day 0 or have day greater than 36, and we expect others won't either" or the like

Please can you outline the basis for the upper bound of 36.

**Comment by dthaler** [comment]
> Please can you outline the basis for the upper bound of 36.

There are no calendars we know of that have months of more than 36 days, especially since the lunar cycle is less than that.  https://en.wikipedia.org/wiki/History_of_calendars discusses many historical calendars, of which under China, it says "In the so-called [five-phase](https://en.wikipedia.org/wiki/Wuxing_(Chinese_philosophy)) calendar, the year consists of 10 months and a transition, each month being 36 days long, and the transitions 5 or 6 days." so there is evidence of a calendar with 36 days per month.
