### ISSUE TITLE
Add EXID to SOURCE_CITATION record 

### ISSUE THREAD

**Issue by cdhorn** [FamilySearch/GEDCOM#114]
The SOURCE_CITATION record definition lacks EXID support.

It is not known to me if Ancestry.com intends to add Gedcom 7 import and export support.  Today they use the _APID custom tag in the SOURCE_CITATION to identify the specific record in the Ancestry.com database in exports so the association can be recreated properly on an import.  If EXID was provided it could ideally be used for that purpose instead in a more standardized manner.

**Comment by dthaler** [comment]
EXID is available in a SOURCE_RECORD but not the more granular SOURCE_CITATION (e.g. a per PAGE id)

**Comment by cdhorn** [comment]
Right, I am aware of that and opened this issue in the hope that in the next revision of the standard it can be added to SOURCE_CITATION as I just provided a potential use case and perhaps others may be identified in the future.

**Comment by tychonievich** [comment]
I assume this would be liked by any platform that has identifiers for specific pages or claims in a source; i.e. a URI not for "the 1910 USA census" but rather "page 10 of the 1910 USA census" or "the claim that Joey Bloggs was a Farmer in the 1910 USA census".
