### ISSUE TITLE
Media files called gedcom.ged incompatible with GEDZIP format

### ISSUE THREAD

**Issue by fisharebest** [FamilySearch/GEDCOM#12]
As previously mentioned in https://groups.google.com/g/gedcomgeneral/c/Hh05Hj8X8Ac

If a GEDCOM file contains a media file named `gedcom.ged` (as per the following example), and the data is then saved in GEDZIP format, then the media file will have the same name as the GEDCOM file (`gedcom.ged`).  Clearly we cannot have two files with the same name.

```
0 @X1@ OBJE
1 FILE gedcom.ged
1 NOTE A family tree supplied by my cousin
```

Originally, I suggested that media is stored in a subfolder in the GEDZIP file.  However, now that 7.0 is issued, this will lead to a significant backwards incompatibility, and I suspect this change is not likely to be approved.

As an alternative, we could state that media files MUST NOT have the name `gedcom.ged`.

**Comment by tychonievich** [comment]
I agree this is a problem with the current spec. As you note, the spec has been released so I thing we ban `gedcom.ged` as a `FILE` payload. I also think it worthwhile to ban `MANIFEST.MF` and all paths beginning `META-INF/`; I see that as the intent of the paragraph mentioning them in the current specification.
