### ISSUE TITLE
Process for registering EXID.TYPE values

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#121]
EXIDs are only interoperable without data loss if implementations use the same EXID.TYPE values to mean the same thing.
Currently there seems to be nowhere that such TYPE values can be listed.  How would one go about registering one for other implementations to use to mean the same thing?

Currently all that seems to exist is https://gedcom.io/migrate/#afn-rfn-rin which lists values for AFN, RIN, and RFN, but how would one add to that set in a non-implementation-specific way?

**Comment by tychonievich** [comment]
To be an EXID, the ID *must* be 

**stably single-value**: a given ID will never be re-used with a different meaning

**unique**: a given meaning always has the same ID

If we register them, we should have some way of tracking those properties

**Comment by dthaler** [comment]
GEDCOM Steering Commitee discussion 3/15/2022: create a new file in the repo with the table, analogous to the table in the version detection spec.   Ideally a machine readable file format.   And the spec should have a pointer to that file for where to register new values.

Do we need a process or step to verify whether EXID vs REFN is appropriate and how do we describe the guidance?   E.g., EXIDs should have some notion of stability of ids.  E.g., we could have columns "Who has attested that IDs are unique?"  and "Who has attested that IDs are durable?"
