### ISSUE TITLE
Recommendations around nicknames

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#134]
Which of the following is preferred, or are all equally preferred?

1)
```
1 NAME Mary /Smith/
2 SURN Smith
2 GIVN Mary
2 NICK Polly
```

2)
```
1 NAME Mary "Polly" /Smith/
2 SURN Smith
2 GIVN Mary
2 NICK Polly
```

3)
```
1 NAME Mary /Smith/
2 SURN Smith
2 GIVN Mary
1 NAME Polly /Smith/
2 SURN Smith
2 GIVN Polly
2 TYPE AKA
```

The answer affects the Compatibility Report Generator in terms of whether it treats two or more of the above as equivalent or not.

**Comment by tychonievich** [comment]
Discussed 2022-04-26:

General consensus that 3 is not the same as the other two.

A possible advisory addendum to the next spec patch could be

> When a `NICK` substructure is present, its payload should be included in the `NAME` superstructure by delimiting it with parentheses like `Mary (Polly) /Smith/` or quotes like `Mary "Polly" /Smith/` (preferably placed after all given names) but may be omitted.

**Comment by tychonievich** [comment]
In drafting a pull request to resolve this, I ran into a few issues.

1. The Personal Name datatype allows any character except `/` anywhere in a name, so a name like `1 NAME G☺"k3“ /J0nes/` is technically allowed. Are we
    1. proposing to leave it unchanged
    2. proposing to change it to treat `""` and `()` specially
2. The current spec says

The personal name datatype does not treat `""` or `()` specially. I assume we are not changing that; if so


1.  ```gedcom
    1 NAME Mary /Smith/
    2 NICK Poly
    2 GIVN Mary
    2 SURN Smith
    ```
4.  ```gedcom
    1 NAME Poly /Smith/
    2 NICK Poly
    2 SURN Smith
    ```
5.  ```gedcom
    1 NAME Mary Poly /Smith/
    2 NICK Poly
    2 GIVN Mary
    2 SURN Smith
    ```

**Comment by tychonievich** [comment]
Questions about implementing this:

1. I assume we are not changing the Personal Name datatype: using quotes and parenthesis is just convention, not official syntax. Is that right?
2. The current spec says
   
    > The `PERSONAL_NAME_PIECES` are provided optionally for systems that cannot operate effectively with less structured information. The Personal Name payload shall be seen as the primary name representation, with name pieces as optional auxiliary information.

   One reading of this is that the `NICK` cannot have data that is absent from and cannot be derived from the `NAME`. If that is the case, then the `NICK` cannot be omitted from the `NAME`

3. The current spec defines `g7:iINDI-NAME` as

    > Names of individuals are represented in the manner the name is normally spoken

   which suggests that we can't recommend quotes or parentheses unless they are used in the culture of the individual.


I think those three points mean that we want to add something like a note (not normative text) to the `g7:NICK` description that says something more vague, like

> In many cultures it is traditional to present a nickname after all given names and to delimit it with quotation marks or parentheses.

**Comment by fisharebest** [comment]
> after all given names

Where the nickname is a diminutive form of the given name, it is common to write it after the corresponding given name.

`1 NAME Stephanie "Steffi" Alice /Smith/`

**Comment by dthaler** [comment]
> > with quotation marks or parentheses.
> 
> May I suggest using just `"` characters.

After experimentation last week, I completely agree.  Parentheses are commonly used for other purposes in genealogical publications, mainly for use of maiden names such as: Mary (Smith) Jones.   I have found that people will enter that into GEDCOM files with the maiden name in parenthesis, and it would arguably corrupt data if the maiden name were treated as a nickname instead.

Quotation marks are commonly used in genealogical publications for nicknames, and their use in GEDCOM for nicknames was explicitly specified in the [GEDCOM 5.4 specification](https://gedcom.io/specifications/[Gedcom5.4.pdf](https://gedcom.io/specifications/Gedcom5.4.pdf)) as Albert pointed out, where it says:

> A nickname can now be included on the name line by enclosing it in double quotation marks. 
...
```
NAME-PERSONAL:= {Size=1:120}
 [
 <TEXT> |
 <TEXT> "<NICKNAME>" |
 "<NICKNAME>" <TEXT> |
 /<TEXT>/ |
 <TEXT> /<TEXT>/ |
 /<TEXT>/ <TEXT> |
 <TEXT> /<TEXT>/ <TEXT>
 ]
```

> A nickname can be included by 
> enclosing the nickname part in double quotes ("). 
>  Examples:
>  William Lee (given name only or surname not known)
>  /Parry/ (surname only)
>  William Lee "Bill" /Parry/

Also I observe that the above example puts the nickname Bill after all given names, not immediately after William.

**Comment by tychonievich** [comment]
Discussed 2022-05-03
Did not come to a final conclusion, but did note that

1. We cannot restrict the use of quotes or add semantics to them in a patch or minor release. Any prescriptive change would have to wait for 8.0, and a larger name revision is being discussed for that version.
2. While quotes may be appropriate in some cultures, parentheses are more common in other cultures. We identified places where other delimiters or no delimiters were used;  situations where nicknames were of varying importance to include in the name; situations where nicknames vary be relationship to the individual or that change over time; etc. We do no immediately see a simple solution to that.

**Comment by dthaler** [comment]
Discussion 10 MAY 2022:
> One reading of this is that the NICK cannot have data that is absent from and cannot be derived from the NAME. If that is the case, then the NICK cannot be omitted from the NAME

Agreement to add a clarifying note but not limit it to NICK
