### ISSUE TITLE
With v7.0.8 "Clarification" individuals without a surname or that use location in their name presents issue!

### ISSUE THREAD

**Issue by Norwegian-Sardines** [FamilySearch/GEDCOM#151]
With the new "clarification" the Personal Name it would seam that individuals that do not have surnames and may also have location type names will not have the use of PERSONAL_NAME_PIECES based on the new definition:

> Clarify that one implication of "The Personal Name payload shall be seen as the primary name representation, with name pieces as optional auxiliary information" is that "all name parts in PERSONAL_NAME_PIECES should appear within the <PersonalName> payload."

Since normally I would enter in a GEDCOM the following for a person without a surename and a location name"

0 INDI 
1 NAME Olaf Olsen Bruflot
1 GIVN Olaf

Without a SURN since they did not have a surname.  But I would need to enter their entire name from birth records <given> <patronymic name> <location/farm name> in the the NAME tag,

His sister would be:
0 INDI 
1 NAME Maria Olsdattr Bruflot
1 GIVN Maria 

The problem is that without a a GIVN tag, reports would be forced to only use the NAME tag on all displays and reports where a given name was normally displayed.   This would be compounded when an individual had multiple given names producing a very long name display: Thorvald Andreas Olsson Bruflot comes to mind!

**Comment by tychonievich** [comment]
Resolved in #161
