### ISSUE TITLE
Recommend SDATE use single Gregorian dates

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#160]
### Discussed in https://github.com/FamilySearch/GEDCOM/discussions/140

Those who have engaged in a discussion about `SDATE` generally agree that sorting is easiest if all sort-by dates are single dates (not ranges or periods) in the same calendar. We cannot change this in a patch or minor release as it is not backwards compatible and we know of applications that allow users to enter any kind of date in a sort-by field, but we can make a recommendation like

> It is recommended that the `SDATE`'s payload be in the Gregorian calendar and be a simple `date` with the `calendar` omitted. Including a `month` and `day` is encouraged to help different applications sort dates the same way, as the relative ordering of dates with different levels of precision is not well defined.

**Comment by dthaler** [comment]
Steering committee discussion 14 JUN 2022:
@dthaler to create a pull request with the following wording.
> Note: it is recommended to use a payload that matches `[[day D] month D] year [D epoch]`. Other `DateValue` forms may have unreliable effects on sorting.  Including a month and day is encouraged to help different applications sort dates the same way, as the relative ordering of dates with different levels of precision is not well defined.
