### ISSUE TITLE
Sorting in INDIVIDUAL_ATTRIBUTE_STRUCTURE and INDIVIDUAL_EVENT_STRUCTURE

### ISSUE THREAD

**Issue by ungeahnt** [FamilySearch/GEDCOM#172]
One question: Is there a specific reason for the sort order in [INDIVIDUAL_ATTRIBUTE_STRUCTURE](https://github.com/FamilySearch/GEDCOM/blob/main/specification/gedcom-03-datamodel.md#individual_attribute_structure-)? It looks like some tags are sorted alphabetically and others are not (e.g. ADOP, BIRT, CHR, EVEN are listed at the very end). Is this intentional?

Same with FACT at [INDIVIDUAL_EVENT_STRUCTURE](https://github.com/FamilySearch/GEDCOM/blob/main/specification/gedcom-03-datamodel.md#individual_event_structure-)

**Comment by ungeahnt** [comment]
My point is about the readability of the GEDCOM specification. 

I had looked for `BIRT `in `INDIVIDUAL_ATTRIBUTE_STRUCTURE `and at first glance found nothing, thinking that the tags in this list were sorted alphabetically. That BIRT appeared at the very end was a bit irritating. Also, I couldn't figure out a rule for this type of sorting. 

A consistent sorting per list/structure incl. a comment in the text would certainly be helpful.

**Comment by albertemmerich** [comment]
It will not be easier if we now modify the ordering of events and/or facts in the spec. We will have a lot of modifications in the document, and these have to be checked whether there is any need to adjust applications which have already implemented these structures. This may be better for those who read the document for the first time, but for all others it makes work more complicated.
