### ISSUE TITLE
Ambiguity about whether a structure URI defines substructures and cardinality

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#178]
So if two places in the spec use the same URI in different contexts, like two places using g7:DATE, then whether all such uses MUST have the same substructure schema or not, doesn't seem to be explicitly called out.

The answer is apparently yes, but I cannot find anywhere in the spec that explicitly says so, and I could only gather this by failure to find any counter examples.  Certainly the files in https://github.com/FamilySearch/GEDCOM/blob/main/extracted-files/tags DO define the substructures and do answer this unambiguously (outside of the spec itself).
But those are just _standard_ structures, so it is ambiguous without an explicit statement that the same constraint applies to all extension structure definitions as well, and to all future standard structures.

The rule is clear for _relocated standard structures_ where the spec says:

> The extension-defined substructures of a relocated standard structure are the substructure types documented in this specification for that structure type, including usual limitations on cardinality, payloads, **substructures**, etc.

But it is not clear whether a _tagged extension structure_ could have a URI whose definition says something like:
"can contain substructure DATE when the tagged extension structure appears in an INDI record, but not when it appears in a SOUR record".   My belief is that we should explicitly disallow this and require using separate URIs when the substructure requirements differ in different contexts.

Section 1.5.2 says:

>  It is recommended that extension creators use URLs as their URIs and serve a page describing the meaning of an extension at its URL.
>
> Future versions may include additional recommendations relating to documentation, machine-readable documentation, or embedded metadata about extensions within the schema.

I'd propose we do so by saying somewhere that the URI also uniquely identifies the requirements around substructures and their cardinality.

**Comment by albertemmerich** [comment]
Dave: "I'd propose we do so by saying somewhere that the URI also uniquely identifies the requirements around substructures and their cardinality."
I agree!

URI like https://gedcom.io/terms/v7/PLAC should be starting for discussions about the recommended content of tag defining URIs. I'd propose we discuss this for the issue of documenting extension tags, issue #175, too.

**Comment by tychonievich** [comment]
As the author of the structure type URIs in 7.0, my intent was

- URIs fully identify whether the tag is a **calendar**, **month**, **enumerated value**, or **structure type**, with additional properties for two of these four uses of tags:
    - **Enumerated value** URIs fully identify the meaning of the enumerated value, regardless of the structure using the enumerated value.
    - **Structure type** URIs fully identify 
        - structure meaning
        - payload type, and
        -  substructures and their cardinality
        
        They do *not* fully identify the cardinality of the identified structure within its superstructure; see e.g. `g7:TYPE` which is `{0:1}` in most events but `{1:1}` in `EVEN` and `g7:NOTE` which is `{0:M}` most places but `{0:1}` in the header.

- The URI of a standard tag can be determined from exactly two data:
    1. The **tag** itself
    2. The nearest **containing structure type** (superstructure for structure type tags, structure it is in the payload of for the others)


The processing scripts that create the files in the `extracted-files` directory are supposed to report any exceptions to these rules, but they are also complicated enough and written hastily enough that I'm not 100% certain they succeed in doing that. However, as I wrote the spec to meet these rules, and have a script that thinks I succeeded, and now have a third party stating I succeeded, I am confident enough that I succeeded to add this information to the specification.

It is not immediately clear to me where in the spec this information belongs. Section 1.2 makes sense for the structure part, but we might need a new section to describe the part about enumeration calendar, and month.

**Comment by tychonievich** [comment]
Discussed in steering committee meeting. To do:

- in section 1.2, add (1) reference to URI of structure type and (2) list of what is controlled by structure type.
- in section on extensions, note that if an extension allows a standard structure as its substructure, it does not have control over the substructures of that standard tag (word this better)
- also find places to note this about enumerated values

**Comment by dthaler** [comment]
I agree that PR #189 addresses this issue and this issue should be closed once 189 is merged.
