### ISSUE TITLE
Define how to parse 5.5 and 5.5.1

### ISSUE THREAD

**Issue by GPHemsley** [FamilySearch/GEDCOM#18]
Given that the changelog admits that [5.5.1 had ambiguities](https://gedcom.io/changelog/#ambiguities-resolved) that were resolved in 7.0, and that 5.5 was the most recent version of the standard for more than two decades, it would be useful if the modern spec were to define how to parse the constructs of the previous versions into the modern format. (Compare, for example, what [HTML](https://html.spec.whatwg.org/multipage/) does.)

That way implementors of the modern spec do not need to go back to the old, and less technically written, specifications in order to support importing data from the older versions of GEDCOM. This would also facilitate the creation of convertors from 5.5 and 5.5.1 to 7.0 and onward.

In addition, this should resolve some of the concerns enumerated in #5 surrounding interoperability concerns.

Of course, this entire discussion hinges on whether providing guidance to implementors is within the scope of the spec. I would argue, given the size of the ecosystem around GEDCOM, that it should be.

**Comment by tychonievich** [comment]
During development of 7.0, we discussed this and decided that at least initially a less formal set of guides (like <https://gedcom.io/migrate/>) would be sufficient to this end, especially if accompanied by some reference code (like <https://gedcom.io/tools/>). Suggested additions to those guides and code would be welcome.

Conversations of the version 7 steering committee about #5 suggested that there was little interest by that team in investing more effort in defining, disambiguating, and documenting 5.5.1 and earlier specs, but that if others wished to work on related projects we'd welcome that collaboration. I expect that decision will apply here too, but I'll bring it up in our meeting today to be sure.

**Comment by tychonievich** [comment]
Discussed in 2021-07-06 meeting; agreed that clarifying 5.5 and 5.5.1 will not be included in 7. Others are welcome to publish their recommendations on how to interpret files that exercise the ambiguities of 5.5 and 5.5.1 files if they wish. For example, the GEDCOM-L group has published an addendum (<https://genealogy.net/GEDCOM/>) that provides one such recommendation.
