### ISSUE TITLE
Can one extension tag be given multiple URIs?

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#181]
Documented extension tags in the current spec (1) allow a set of tag-to-URI mappings, (2) state that a tag with such a mapping can be changed without changing the meaning of the file.

From that we can deduce that having two tags that map to the same URI has no meaning beyond having a single tag map to the URI. Hence, a recommendation of one tag per URI would be acceptable.

However, there is an ambiguity about having the possibility of more than one URI per tag. Nothing in the spec forbids it, but nothing in the spec explains what to do if it happens. Given something like

```gedcom
0 HEAD
1 GEDC
2 VERS 7.0.9
1 SCHMA
2 TAG _A https://example.com/problem
2 TAG _A https://example.com/flaw
0 @I1@ INDI
1 _A @A1@
0 @A1@ _A
1 NOTE there's a problem here
```

what should an application do? Discard it as problematic? Look up the two URIs and try to deduce which one can be a record? Something else?

The easy fix would be to forbid this behavior: each extension tag may appear in the schema at most once.

However, standard structures (#178) and undocumented extension tags (probably; see #180) do allow tag re-use, so maybe documented extension tags should too?

In the 7.0 spec, sometimes using the same tag for different meanings was done to minimize changes from 5.5.1 (e.g. `g7:enum-ADOP-HUSB` vs `g7:enum-HUSB`, `g7:HEAD-PLAC-FORM` vs `g7:PLAC-FORM` vs `g7:FORM`), but there are a few use-cases we might want to continue permitting with extensions:

* If a structure points to a record, and if there is only one way that the record can be related to the superstructure of the pointer, then we used the same tag for both the pointer and the pointee: examples include `SOUR`, `OBJE,` and `SNOTE`, as well as some common extensions like `_LOC`.

    As an aside, when there are multiple ways they might be related, separate tags are used: examples include `CHIL`, `FAMS`, `ASSO`, and `ALIA`.

* We sometimes used the same tag for a structure type and an enumerated value with related meanings: examples include `MAP`, `WIFE`, and `CHIL`.

I see several possible paths forward:

1. We explicitly ban a single extension tag having 2+ URIs in a single schema. If we decide to port `_LOC` to use URIs we'll have two URIs, once for LOC record and one for LOC pointer, and require two separate tags to achieve that.

2. We explicitly permit reuse of documented extension tags with some explanatory text like "if the same extension tag is given multiple URIs in the schema, the meaning associated with each URI must define mutually-exclusive contexts where they can be used." That text is too vague, and a full definition would likely require a list like "the URI of up to one calendar, one month per calendar, one enumerated value per containing structure type, and one structure type per superstructure type".

3. In a future minor version of the spec, add a `TAG`.`CONTEXT` structure with a URI payload and require the schema keep each tag+context pairing unique. For this to be a minor version it would have to be coupled with the ban in option 1 above in the current version.

**Comment by albertemmerich** [comment]
Good point!
Path 1. would forbid structures in extension tags, which the standard uses for standard tags. _LOC is an example for this. As there are already GEDCOM files using _LOC (in both ways: as pointer and as record), this is no solution for 7.x
Path 3. makes SCHMA even more complicated as it is. If we can we should not do that.

Path 2. is the way which the GEDCOM 7.0 standard uses for the standard tags: Defining multiple URIs per tag, if the tag is used in different context. I would allow that for extension tags, too. And use it for _LOC.
The exporting application is responsible to give URIs for an extension tag, which uniquely describe the context, meaning, payload, and substructures of the tag. If a tag is used in more than one context, the URIs are defined for each of them. Every context needs its own URI. This was done in the URIs of standard tags and should be done with exTags, too.

**Comment by tychonievich** [comment]
Running with the path-2 idea and the `_LOC` example, we might have something like

```gedcom
0 HEAD
1 GEDC
2 VERS 7.0.9
1 SCHMA
2 TAG _LOC https://example.com/LOC-record
2 TAG _LOC https://example.com/LOC-pointer
0 @I1@ INDI
1 BIRT
2 PLAC Atlantic, Earth
2 _LOC @L1@
1 UID 68949462-a184-44c2-bd4b-1ef6ee8d6aec
0 @L1@ _LOC
1 NAME The Atlantic Ocean
1 _LOC @L2@
0 @L2@ _LOC
1 NAME Earth
0 TRLR
```

If an application understands `_LOC`, this works fine.
If an application does not understand `_LOC`, it cannot tell which structure has which type.
However, if it merges it with another file that uses the tag `_LOC` in a different way, such as


```gedcom
0 HEAD
1 GEDC
2 VERS 7.0.9
1 SCHMA
2 TAG _LOC https://another.example.com/gedcom.html#level-of-confidence
0 @I2@ INDI
1 BIRT
2 PLAC Atlantic, Earth
2 _LOC 45%
1 UID 68949462-a184-44c2-bd4b-1ef6ee8d6aec
0 TRLR
```

then the even a program that understands neither can still merge the files, as 

```gedcom
0 HEAD
1 GEDC
2 VERS 7.0.9
1 SCHMA
2 TAG _LOC1 https://example.com/LOC-record
2 TAG _LOC1 https://example.com/LOC-pointer
2 TAG _LOC2 https://another.example.com/gedcom.html#level-of-confidence
0 @I1@ INDI
1 BIRT
2 PLAC Atlantic, Earth
2 _LOC1 @L1@
2 _LOC2 45%
1 UID 68949462-a184-44c2-bd4b-1ef6ee8d6aec
0 @L1@ _LOC1
1 NAME The Atlantic Ocean
1 _LOC1 @L2@
0 @L2@ _LOC1
1 NAME Earth
0 TRLR
```

Examples like this convince me that path 2 is doable.

However, examples like this also make me wonder why not just do path 1? Because documented extension tags can be changed without changing meaning as long as the URIs don't change, why not have serialized the first example as something like the following?

```gedcom
0 HEAD
1 GEDC
2 VERS 7.0.9
1 SCHMA
2 TAG _LOCR https://example.com/LOC-record
2 TAG _LOCS https://example.com/LOC-pointer
0 @I1@ INDI
1 BIRT
2 PLAC Atlantic, Earth
2 _LOCS @L1@
1 UID 68949462-a184-44c2-bd4b-1ef6ee8d6aec
0 @L1@ _LOCR
1 NAME The Atlantic Ocean
1 _LOCS @L2@
0 @L2@ _LOCR
1 NAME Earth
0 TRLR
```

I suppose the advantage of path 2 over path 1 is that applications that ignore the URIs but check the tags are more likely to get the right meaning (which was also the intent of the text in section 1.5.1 "it is recommended that documented extension tags not be changed.")

**Comment by albertemmerich** [comment]
I agree to last statement about advantage of path 2 over path 1: For compatibility reasons it would be more clear to stay with the names of extension tags defined and/or used in 5.5.1. A lot of programs know what _LOC is (pointer and record), they do not know what _LOC1 and _LOC2 should be.
So path 2 (including not modified tag names) is working with applications ignoring the tag URIs as well with applications using the URIs. If the applications follow the recommendation to do not modify documented tag names, this advantage will stay with the data.

**Comment by tychonievich** [comment]
Discussed in steering committee

We think this issue will be more easily resolved once we have an extension tag registry (#175), which in turn depends on us having a well-defined YAML format (#183 and #184)

**Comment by tychonievich** [comment]
Discussed in steering committee

- We do intend to allow one tag to have multiple URIs provided that the extension defines them to appear in disjoint contexts.
- Applications that do not understand the extension should assume that when merging files, each files extensions might appear in the same context and rename conflicting extension tags accordingly.
- We will write up a pull request to make this more explicit as a patch to the standard.
