### ISSUE TITLE
tag defining URI: context versus superstructures

### ISSUE THREAD

**Issue by albertemmerich** [FamilySearch/GEDCOM#182]
URIs in GEDCOM 7.0 define tags including their superstructures. See long lists in https://gedcom.io/terms/v7/SOUR or in https://gedcom.io/terms/v7/RESN.
However: This contradicts the FAQ solution shown in https://gedcom.io/techfaqs/#how-do-i-mark-a-parent-child-relationship-as-confidential as there the URI for RESN is used with another superstructure as defined in the URI.

I think we need to explain, that the listed superstructures in the URIs are non-exclusive and do not show superstructures which may be defined in URIs for extension tags.
Another solution would be to eliminate the superstructures and to describe the context for the tag. But I think the lists of superstructures are good as information as lang as they are declared non-exclusive and only covering the standard structures.

In same way the substructures shown in the standard URIs are non-exclusive: It is permitted to define extension tags as substructure of the tags, and by this the list of substructures is not complete. Or should we add to each list of substructures an element allowing URI-defined extension tags as additional substructures?

**Comment by tychonievich** [comment]
This issue brings up one of many problems with the YAML files (see #183 for an issue tracking those), as well as a more general problem.

Extension structure types can be both subtypes and supertypes of existing structures. Thus, to define how an extension fits into the data model without modifying the existing structure definitions, we need to be able to list both substructures and superstructures. If either one is listed, the relationship should be permitted; e.g.

- if `_LOC-record` lists substructure `g7:NAME` then ` g7:NAME` can be used in a `_LOC-record` even if it isn't listed as one of `g7:NAME`'s superstructures.
- If `_RUFNAME` lists superstructure `g7:INDI-NAME` then `_RUFNAME` can be used in `g7:INDI-NAME` even if it isn't listed as one of `g7:INDI-NAME`'s substructures.

Similarly for enumerations: extension value `_ENEMY` should be able to list itself as a new payload for standard structure `g7:ROLE`, and extension structure `_FOSTERED_BY` should be able to list standard value `g7:enum-BOTH` as one of its valid enumeration values, both without requiring the existing structure/value type to be updated.

As one additional example of the non-exhaustive nature of the substructure/superstructure listings in the YAML, relocated standard structures can be used even if neither the substructure nor the superstructure documents their use. I do not see a need for a similar feature for extension structures: I assume the person wishing to relocate them could, update the extension definition. I also do not know of a use case for relocated enumeration values.

**Comment by tychonievich** [comment]
Resolved by #188
