### ISSUE TITLE
INDI:NATI Definition Change from v5.5 and v5.5.1

### ISSUE THREAD

**Issue by Norwegian-Sardines** [FamilySearch/GEDCOM#186]
In GEDCOM v5.4, v5.5 and v5.5.1 the definition of the INDI:NATI tag is:

>NATIONAL_OR_TRIBAL_ORIGIN:= {Size=1:120}
The person's division of national origin or other folk, house, kindred, lineage, or tribal interest. Examples: Irish, Swede, Egyptian Coptic, Sioux Dakota Rosebud, Apache Chiricawa, Navajo Bitter Water, Eastern Cherokee Taliwa Wolf, and so forth.
>

in GEDCOM v7.0.8 it is now:
>The national heritage of an individual.

The loss of several “divisions” for house, kindred, lineage and tribe removes functionality and changes a long time use that involves personal identity.  Please correct this by including an updated definition in the next release.

I’ve used this definition since it’s inclusion in the v5.4/5.5 time frame!

**Comment by tychonievich** [comment]
5.5.1 provides two definitions:

- page 90 has 7.0's current text, "The national heritage of an individual."
- page 56 has the text @Norwegian-Sardines quoted: "The person's division of national origin or other folk, house, kindred, lineage, or tribal interest" with examples.

I agree that we should use the more inclusive text
