### ISSUE TITLE
Inconsistency with ENUMs, PHRASEs and OTHER

### ISSUE THREAD

**Issue by fisharebest** [FamilySearch/GEDCOM#195]
Some ENUM values include the value `OTHER`, and also allow a `PHRASE` subtag.

However, three elements allow a `PHRASE` subtag, but **do not** allow a value of `OTHER`.

For consistency, I think we should allow `OTHER` as the alternative would be to leave the element empty.

* `g7:FAMC-STAT`.  Here, it seems reasonable to add `OTHER` to the list of values.

* `g7:FAMC-ADOP`. Given the current values, `HUSB`, `WIFE`, `BOTH`, I cannot think of what other value might be needed.   So either add `OTHER` or remove `PHRASE`.

* `g7:SOUR-EVEN`. Given the current definition "the type of event or attribute", I cannot think of what other value might be needed.   So either add `OTHER` or remove `PHRASE`.

**Comment by tychonievich** [comment]
Enumeration values besides `OTHER` can have a `PHRASE`; an example of this is present in the spec

```gedcom
2 ROLE FRIEND
3 PHRASE best friend
```

Hence, while `OTHER` needs a `PHRASE`, `PHRASE` may also be included where there is no `OTHER`. 

That said, it may be worth revisiting the placement of `OTHER` and `PHRASE`. I no longer recall the details of why we made the decisions we did, but can see 

- `g7:FAMC-ADOP`.`PHRASE` with pre-interpreted references, such as `BOTH` with `PHRASE by the Jones family` or `WIFE` with `PHRASE Mrs. Eli Whitkower`

- `g7:SOUR-EVEN`.`PHRASE` with clarity beyond event type, like `PHRASE clerk's copy, not original record` or `PHRASE primarily documents officator's activities; the couples being married were secondary`

I'm unsure about adding `OTHER` to `g7:FAMC-STAT`. I see the value in adding `PHRASE`s wthout picking one of the three current values. But as-is, `g7:FAMC-STAT` provides something of an ordering of confidence (`PROVEN` > no-`STAT` > `CHALLENGED` > `DISPROVEN`) and can be used to influence display, for example by hiding low-confidence links at a user-selected confidence level. If we add `OTHER` it doesn't seem to belong in that order in any obvious way. If we do want to add another value to allow phrases without using one of the current values, I'm tempted to pick one that fits in the hierarchy: maybe something like `UNCHALLENGED` or `DEFAULT` with an explicit statement that this is the implied meaning of a missing `STAT` too.

**Comment by tychonievich** [comment]
Discussed in steering committee; we liked the idea of adding a fourth `g7:FAMC-STAT` value in 7.1 to fill the gap in the current three. We did not reach consensus on the other two examples

**Comment by tychonievich** [comment]
#224 has made some progress on this by adding "unchallenged", but an open item remains:

> Discussed 2022-10-18
> "Unchallenged" and "unknown" are not the same idea, so this is not the correct solution yet. We might be able to come up with some kind of "none of the above" value (perhaps OTHER), or might need to add two values.

**Comment by WGroleau** [comment]
"_g7:FAMC-ADOP. Given the current values, HUSB, WIFE, BOTH, I cannot think of what other value might be needed. So either add OTHER or remove PHRASE_"

PARTNER for unmarried couples.
SPOUSE when gender is unknown

Are "mistress" and "concubine" politically incorrect?
sperm donor?
surrogate mother? 
is there a male equivalent for "mistress"?  "mister" would be misleading, given current usage.

**Comment by tychonievich** [comment]
Discussed in steering committee

The proposal to add `FAMC`.`STAT UNCHALLENGED` is not making progress. If it's defined as "same as no `FAMC`.`STAT`" then it has no obvious value. If it has a different meaning we don't know how to define it.

The rest of the ideas in this issue appear to be resolved in the discussions above: `PHRASE` is useful in cases where `OTHER` is not allowed, and we do not see a motivating use case for adding `OTHER` in these places.

In re `HUSB`, `WIFE`, and `BOTH` these are not about relationships: they are indicating a particular INDI pointer inside the FAM record. OTHER cannot indicate a specific substructure of the FAM and is not appropriate in that context.
