### ISSUE TITLE
Is there a left-to-right bias in date ranges?

### ISSUE THREAD

**Issue by emyoulation** [FamilySearch/GEDCOM#208]
In the data migration from GEDCOM 5.5.1 to 7.0 notes, it explicitly states that there is a left-to-right bias when storing date ranges. (That is, the earlier  date in a "bet x and y" date range must be in the left-hand "x" position and the later in the "y" position.
https://gedcom.io/migrate/#date-ranges

Is that bias states somewhere in the GEDCOM 7 spec? Or is the migration page incorrect?

How is such a left-to-right bias handled in languages written right-to-left? And is there a test specified for ranges spanning the zero point in calendars and ranges exclusively on the negative side?

**Comment by dthaler** [comment]
> In the data migration from GEDCOM 5.5.1 to 7.0 notes, it explicitly states that there is a left-to-right bias when storing date ranges. (That is, the earlier date in a "bet x and y" date range must be in the left-hand "x" position and the later in the "y" position. https://gedcom.io/migrate/#date-ranges
> 
> Is that bias states somewhere in the GEDCOM 7 spec? Or is the migration page incorrect?

The migration page is correct and it quotes where the GEDCOM 7 spec does so.
It's in [section 2.4](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#date) in the production/meaning table which has:

<html>
<body>


BET x AFT x | Exact date unknown, but no earlier than x.
-- | --
AND x BEF x | Exact date unknown, but no later than x.


</body>
</html>

> How is such a left-to-right bias handled in languages written right-to-left? 

The labels "BET", "AND", etc. appear literally in the gedcom file, not in other languages.
So whatever the answer is to the question, it is not seem to be a question about GEDCOM per se, but rather about what might be displayed to humans in a UI.

> And is there a test specified for ranges spanning the zero point in calendars and ranges exclusively on the negative side?

I don't think there's one on gedcom.io yet but this is a good suggestion.

**Comment by emyoulation** [comment]
The way that table is written (with "x" reused) is ambiguous. Given that 5.5.1 has been insensitive to whether the upper/lower limit was on the left or right and that form has more than 20 years of momentum, a subtle change should be WAY more explicit in the Specification.

Or maybe the bias should just be eliminated for flexibility's sake.

If an explicit order was desired, the format should support a concatenated form like:
 AFT x AND BEF y

If the spec remains that inflexible, the test cases should include an intentional fail for date ranges. So that there is a structured verification that the validator in any new tool doesn't perpetuate badly formatted data.

**Comment by tychonievich** [comment]
> The way that table is written (with "x" reused) is ambiguous.

A fair point. I'll create a pull request that doesn't merge identical cells in the table.

>  Given that 5.5.1 has been insensitive to whether the upper/lower limit was on the left or right and that form has more than 20 years of momentum,

So far as we could determine when drafting 7.0, very few applications interpreted 5.5.1 (or any of the other 5.x specs) that way. In all 5.x specs all examples are in the form standardized by 7.0, and a weak argument can be made that that order is required by the explicit order of `FROM`/`TO` and the statements that `FROM`/`TO` differs from `BET`/`AND` "in that the date range is an estimate that an event happened on a single date somewhere in the date range specified" -- which some read to mean they differed *only* in that detail, not in also allowing more flexible date orders.

In 7.0 we thus decided to disambiguate in favor of what appeared to be the common practice: `BET x AND y` means `x <= date <= y` not `min(x,y) <= date <= max(x,y)`

>   the format should support a concatenated form like: `AFT x AND BEF y`

That would have been clearer for those reading the long forms of the tags in English, certainly. But it also would have broken more existing code.

**Comment by tychonievich** [comment]
Discussed in steering committee

Merged a change that removes the table cell ambiguity.

Discussed hosting a test file on gedcom.io that has invalid dates, but decided that in general hosting incorrect files leads to complexities we are not yet ready to handle. Third parties are welcome to create and share such invalid example files.
