### ISSUE TITLE
Replace "rich-text" because it implies RTF format?

### ISSUE THREAD

**Issue by emyoulation** [FamilySearch/GEDCOM#25]
The description that uses rich-text as a type of note can be misinterpreted as indicating Microsoft's RTF format is one of the supported MIME types.

Suggest rephrasing to something like 'styled text in notes' or 'markup text in notes' or (most accurately) 'notes with minimal HTML markup'. 

Page 7: Purpose for Version 7.x
"Add better multimedia handling, negative assertions, and rich-text notes."

**Comment by tychonievich** [comment]
A good suggestion. Implemented in commit 8a37637
