### ISSUE TITLE
DATE include an "OR"

### ISSUE THREAD

**Issue by Norwegian-Sardines** [FamilySearch/GEDCOM#253]
Very often we see in the wild were sources have conflicting dates.  To record these dates people can take several different but in my mind unsatisfactory avenues to record these dates.  For example birth: different censuses could indicate two different years.

1) Multiple Event/Fact entries.  Create two BIRT events each with separate years and sources.
2) Use EST.  Use one of the two dates and include both sources
3) Use ABT. Use one of the two dates and include both sources
4) USE BEF. Use the last of the two dates and include both sources

None of these make for a good recording of the facts found in the source.  Either by only recording one date and potentially overlooking the other, or by creating two fact entries that could be misconstrued as one being favored over the other.

An alternative could be:

1 BIRT
2 DATE (date1) OR (date2)
2 SOUR (source1)
2 SOUR (source2) 

If GEDCOM requires a leading Date Restriction this could be designed as:

1 BIRT
2 DATE CONF (date1) OR (date2)
2 SOUR (source1)
2 SOUR (source2) 

CONF = Conflicting

Most Events can occur multiple times (except birth and death), therefore the GEDCOM file could contain multiple entries of an Event type each being an actual event occurrence.  However, an event could have occurred once but have conflicting date information.  If two event entries are made for a conflict they can be misconstrued as two separate events, rather than a conflict of two dates.  Allowing “OR” would keep the singular event with two conflicting date as one entry.

**Comment by dthaler** [comment]
My view is that "Multiple Event/Fact entries" is the current answer and the other options are worse as they lose information.  Furthermore the same can occur with different places for an event (e.g., different birthplaces being recorded in different US censuses), so it is not really specific to `DATE`.

If the disadvantage is "creating two fact entries that could be misconstrued as one being favored over the other" then using OR doesn't change that.   Any time there are alternatives, one could misconstrue one (e.g., the first one listed) as being favored over the other.

**Comment by fisharebest** [comment]
...and if you had three or more conflicting dates, would you use `DATE A OR B OR C ....`?

> My view is that "Multiple Event/Fact entries" is the current answer

I agree.

**Comment by tychonievich** [comment]
Discussed in steering committee

We agree with the two comments above that the OR construction is not advisable. Given two sources of an event with two different dates (or two different places, officiators, etc) the current model is to have two different event structures.

We acknowledge that this does not allow us to assert "only one of these is right, we don't know which one" but that is a larger issue than dates (in principle it could apply to almost any structure) and would require a more holistic solution, one for which we do not yet have a proposed design.
