### ISSUE TITLE
g7:HEAD-LANG

### ISSUE THREAD

**Issue by WGroleau** [FamilySearch/GEDCOM#267]
Spec (20 Jan 2023) allows only one LANG in the HEAD, saying any items without a LANG modifier should be assumed to be the single LANG in the HEAD.

I suspect I’m not the only one who has person names and place names in more than one language without LANG modifiers (which weren't allowed in 5.5.1).  I suggest to avoid people having to do massive updates, that HEAD-LANG be allowed to be multiple.  Items without a LANG modifier would be assumed to be one of the languages in HEAD-LANG.  Users can be advised (but not required) to add LANG to any item that is ambiguous and required to do so only if it is not a language in HEAD-LANG.

**Comment by WGroleau** [comment]
My HEAD currently has 1 LANG English French but that is not really compliant with 5.5.1 (and spelling out the language name is not complain with g7)

**Comment by tychonievich** [comment]
Discussed in steering committee

If a document does not have a a single default language then it should not use the `g7:HEAD-LANG` structure (or equivalently include it with payload `und` for "language unknown"). We did not see any immediate value in having *multiple* default languages in a single document. Default language is used algorithmically for things like locale-specific sorting, number formatting, and hyphenating; given that usage it is not clear to us what having more than one default language means.

If we have missed something in your issue, please re-open this issue.
