### ISSUE TITLE
MARR.TYPE - "Common-law"

### ISSUE THREAD

**Issue by fisharebest** [FamilySearch/GEDCOM#27]
The specification gives this example of `MARR.TYPE`

```
0 @I1@ INDI
1 MARR
2 TYPE Common Law
```
This is clarified by the text

> This classifies the entry as a common law marriage but the event is still a marriage event.

Elsewhere, it defines `MARR` as

> A legal, common-law, or customary event that creates a family unit of a man and a woman as husband and wife.

Now, according to [wikipedia](https://en.wikipedia.org/wiki/Common-law_marriage), a common-law marriage is one  "not formally recorded with a state or religious registry, nor celebrated in a formal civil or religious service".

Therefore a common-law marriage is NOT an event.  It does not occur on a date.  The specifcation says "events are things that happen on a specific date."

Also, it is not a marriage.  It is specifically the state of being not-married (but living as if you are).

I think this is a poor example and should be removed.  Better examples might be "Civil marriage", "Religious marriage", "Registered partnership", etc.

**Comment by tychonievich** [comment]
This text is quoted verbatim from the 5.5.1 spec, page 49, itself an expansion of the 5.5 spec page 43. But I agree that it is confusing and should probably be changed.

**Comment by tychonievich** [comment]
Discusses 2021-08-11
We identified that common-law marriages are legally recognized as marriages with dates (making them events) in some jurisdictions, but we also agreed that this is a confusing example and probably worth changing.
