### ISSUE TITLE
Tag Name Errors in Text of "Specification, 7.0.11"

### ISSUE THREAD

**Issue by tomsedory** [FamilySearch/GEDCOM#271]
There are two incorrect tag names in _The FamilySearch GEDCOM Specification, 7.0.11_, "3.3.4. Structure types", p72. The errors exist in both the HTML and PDF formats. They appear to be copy / paste errors from the `DESC` tag line above. The two errors are as follows:
`EDUC` (Description)
`EMIG` (Description)

These should correctly read as follows:
`EDUC` (Education)
`EMIG` (Emigration)

(Note: I am re-teaching myself how to code after many years away, so I don't yet feel qualified to submit a pull request. I hope you are OK that I am simply submitting this text error so someone with skills can fix it. I only noticed the error because I am also into genealogy and was reading this new GEDCOM spec. GitHub seemed like the only place to submit feedback. If there is a someone else I should inform, please let me know.)

**Comment by dthaler** [comment]
Thanks for catching this Tom!  Yes, this is the right place to file issues.
