### ISSUE TITLE
Version Detection Character Code error

### ISSUE THREAD

**Issue by rgw16** [FamilySearch/GEDCOM#276]
In version-detection/version-detection.md the following segment contains code 49 (letter I) where the Explanation text shows the numeral 1.

## Version Detection

To detect the GEDCOM file version, perform the steps below, using the character width and byte order determined
above.  If the end of the file is reached before
all steps can be successfully completed, the file is not a valid GEDCOM file.

1. Read until one of the following byte sequences is detected ("1 GEDC"):

Width | Order | Byte sequence to look for           | Explanation
----- | ----- | ----------------------------------- | ------------
2     | LE    | **49** 00 20 00 47 00 45 00 44 00 43 00 | "1 GEDC"
2     | BE    | 00 **49** 00 20 00 47 00 45 00 44 00 43 | "1 GEDC"
1     | (N/A) | **49** 20 47 45 44 43                   | "1 GEDC"
1     | (N/A) | **49** 20 53 59 53 54                   | "1 SYST"

The bolded numbers 49 above should be 31.

In paragraph 3 the text "2 VERS" is rendered using the value 32 for the numeral 2.

3. Continue reading bytes until the following byte sequence is detected ("2 VERS "):

Width | Order | Byte sequence to look for
----- | ----- | --------------------
2     | LE    | 32 00 20 00 56 00 45 00 52 00 53 00 20 00
2     | BE    | 00 32 00 20 00 56 00 45 00 52 00 53 00 20
1     | (N/A) | 32 20 56 45 52 53 20

Could you advise me if I should provide a pull request for this change.

**Comment by tychonievich** [comment]
Thanks for catching this! A pull request would be welcome
