### ISSUE TITLE
EVENT_DETAIL.UID intention

### ISSUE THREAD

**Issue by jl5000** [FamilySearch/GEDCOM#279]
I notice we are able to give unique IDs to EVENT_DETAIL structures via the UID tag. Is the intention to use this in much the same way as XREF pointers by defining EVENT_DETAIL (with UID) once in a record, and then reducing duplication by referring to this UID for other EVENT_DETAILs?

If this is the case, I think this is a great development and there should probably be some text making this explicit with EVENT_DETAIL because at the moment it's only implied.

**Comment by jl5000** [comment]
I've just realised that this probably isn't the case after all since there's no way of differentiating between a UID as an identifier and a UID as a pointer. This begs the question what it's actually used for, and if a future version of EVENT_DETAIL should include a UID pointer.

**Comment by tychonievich** [comment]
UID is widely implemented (it was the single most common extension to 5.5.1), so I'm not sure I know all the ways it is used, but the use case I've heard discussed the most is to disambiguating file merges. If someone sends me an updated GEDCOM with a structure that has the same UID as one I have, that indicates an intent to update that structure; if it has a different UID, that indicates an intent to create an new structure.
