### ISSUE TITLE
Rename `NATI` to match its definition

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#314]
The structure with the `NATI` tag is defined as

| Version | Name | Definition |
|-|-|-|
| 5.0, 5.3 | Nationality | The national heritage of an individual. |
| 5.4, 5.5, 5.5.1 | National or Tribal Origin | The person's division of national origin or other folk, house, kindred, lineage, or tribal interest. Examples: Irish, Swede, Egyptian Coptic, Sioux Dakota Rosebud, Apache Chiricawa, Navajo Bitter Water, Eastern Cherokee Taliwa Wolf, and so forth. |
| 7.0 | Nationality | An individual’s national heritage or origin, or other folk, house, kindred, lineage, or tribal interest. |

Despite the broadening definition over time, the name for the tag was reverted to 5.3's name with 7.0. I propose changing that name (only, not the definition) to one that batter captures the meaning of the structure, such as
 
- **people**, in the older sense when "people" and "persons" were distinct concepts
- **heritage**, though the English of this is much too broad, including things like inheritances
- **birth affiliation**, except you can be inducted into a tribe or naturalized into a nationality
- **affiliation**, except many affiliations (like clubs and political parties) are not encoded with NATI now
- **national affiliation / tribal identity**, chosen so its initials spell the tag NATI

None of these names strike me as ideal. Any preferences or suggestions?

**Comment by Norwegian-Sardines** [comment]
I like to think of these as Cultural Heritages, Cultural Affiliations, Cultural Identity.

The examples are Cultural in nature, and looks to how an individual Identifies themself, which may not be in total just using national boarders or even nations that exist on the map today.  A person could be German and not live in Germany, or Roman and live in what became England.

**Comment by dthaler** [comment]
@tychonievich Can this issue be closed or was there anything else not covered by PR #319?

**Comment by dthaler** [comment]
Closing per discussion March 7, 2024
