### ISSUE TITLE
Allow pointer payloads to AUTH

### ISSUE THREAD

**Issue by WGroleau** [FamilySearch/GEDCOM#356]
Several of my SOURces are family histories written by relatives.  I find it useful to put (for example)
`1 AUTH @P517@`
in the SOUR record.  Applications could optionally display the name, and/or support an easy jump to that person's record.

**Comment by dthaler** [comment]
Discussion in GEDCOM Steering Committee 22 FEB 2024:
* Different cataloging systems use "author" to refer to different concepts, so author is somewhat ambiguous.
* Sometimes an "author" of a source is an organization, such as a family organization.
* An extension can be used in GEDCOM 5.5.1 and FamilySearch GEDCOM 7.0.  Feel free to do so and register it (see https://github.com/FamilySearch/GEDCOM-registries?tab=readme-ov-file#registering-extensions) so others can potentially do the same.  As noted there, if multiple applications/websites start using it then it is a candidate for future standardization.

**Comment by dthaler** [comment]
We believe this question has been answered and there are currently no further actions for the Steering Committee unless/until there are multiple applications using a defined extension for this feature.  We have created a tag "awaiting use" to make it easy to search for all closed issues in this state, that could potentially be reopened in the future once there is sufficient evidence of use.
