### ISSUE TITLE
Placement of EVENT_DETAIL

### ISSUE THREAD

**Issue by jl5000** [FamilySearch/GEDCOM#358]
Please could we reposition EVENT_DETAIL in INDIVIDUAL_EVENT_DETAIL to come after the age/phrase (and update the sample files)? This would make it consistent with FAMILY_EVENT_DETAIL.

**Comment by tychonievich** [comment]
Discussed in steering committee

We agree this would be a nicer order of the lines in the spec, but worry that changing specification-defining lines might be flagged as a change to the spec by some developers, despite not change to the specified files, and thus have chosen to defer making the fix until version 7.1

**Comment by dthaler** [comment]
This is now fixed in the next-minor branch and will be part of whatever the next version post 7.0 will be.
