### ISSUE TITLE
Requirement re "shared on the web" can't be a requirement

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#401]
The current spec includes (emphasis added)

> Machine-local files must not be used in [FamilySearch GEDZIP](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#gedzip) **nor when sharing datasets on the web or with unknown parties**, but may be used for close collaboration between parties with known similar file structures.

This makes a requirement on the file based on an unknowable constraint of how the file will be used, and thus a requirement that cannot be satisfied in general. It should be weakened to a recommendation instead.

**Comment by dthaler** [comment]
@albertemmerich is this ok to close now that #406 is merged?

**Comment by dthaler** [comment]
Discussion 12/28/2023: committee believes this issue is now addressed.  @albertemmerich please reopen if you disagree.  Thanks!
