### ISSUE TITLE
NON_EVENT_STRUCTURE - family/individual events

### ISSUE THREAD

**Issue by fisharebest** [FamilySearch/GEDCOM#416]
Both `INDI` and `FAM` records allow a `NO` event, whose value is [g7:enumset-EVEN](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#enumset-EVEN)

`enumset-EVEN` lists all individual and family events.

This implies that you can use any event on either record type.  e.g.

```
0 @@ INDI
1 NO MARR

0 @@ FAM
1 NO BAPM
```

Should the specification be clear that only `INDI` facts are acceptable in `INDI.NO`?

**Comment by tychonievich** [comment]
I think we have a fix for this in next-minor (as pat of adding NO NAME) that is not yet in main

Main's text:

> #### `NO` (Did not happen) `g7:NO`
>
> An enumerated value from set `g7:enumset-EVEN` identifying an event type which did not occur to the superstructure's subject. See `NON_EVENT_STRUCTURE` for more details.


Next-minor's text:

> #### `NO` (Negative assertion) `g7:NO`
>
> An enumerated value from set `g7:enumset-NO` identifying something that was not part of the superstructure: an event type which did not occur to the superstructure's subject, that the superstructure's subject did not have an name or name part, etc. A specific payload `NO XYZ` should only appear where `XYZ` would be legal.
>
>See `NEGATIVE_ASSERTION` for more.

**Comment by dthaler** [comment]
Discussion in GEDCOM Steering Committee 1/18/2024:
* The sentence in next-minor also should apply to main: "A specific payload `NO XYZ` should only appear where `XYZ` would be legal."
* We aren't splitting `g7:enumset-NO` into two at this point because that would be a breaking change and could only be done in next-major.
