### ISSUE TITLE
g7:datatype-FilePath does not exist

### ISSUE THREAD

**Issue by dctaylor87** [FamilySearch/GEDCOM#465]
The 7.0.14 version of the spec mentions g7:datatype-FilePath on page 106 (in the description of GEDZIP).
According to the URIs and Prefix Notation section , g7: is to be interpreted as

https://gedcom.io/terms/v7/

But, https://gedcom.io/terms/v7/datatype-FilePath does not exist.  Either the name is wrong or the file
is missing.

**Comment by dthaler** [comment]
Good catch, it should be g7:type-FilePath.
https://gedcom.io/terms/v7/type-FilePath does exist.
