### ISSUE TITLE
Clarify meaning of PLAC when FORM does not exist

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#486]
See https://github.com/FamilySearch/GEDCOM/discussions/483

The spec has a gap in its wording; if a PLAC has not FORM and there's not HEAD.PLAC.FORM then the definition of PLAC gives it no meaning. We should fix that ambiguity.

**Comment by Norwegian-Sardines** [comment]
In my experience `PLAC`.`FORM` is never used by the big software companies and even with the software I use the concept of “jurisdiction” has little or no relevance. 

IMHO, the `PLAC` tags gets more use in mapping a location and can include cemeteries and churches (not necessarily a jurisdiction).

For my purposes and many other people I talk to, the `PLAC` tag will include addresses, building names, church names, cemetery plot locations and other locations not considered a jurisdiction nor are the regular and consistent (always the same for all instances).

Until a better way to create a location concept that allows for a shared repository of locations used in the GEDCOM file (possibly similar to GEDCOM-L “Location_Record”) enhancing the definition of the `PLAC` tag may not be necessary.  The `PLAC` tag needs more thought and normalization.

**Comment by Norwegian-Sardines** [comment]
I agree with your additional definition!
