### ISSUE TITLE
Source_Citation SOUR.DATA.DATE has no definition.

### ISSUE THREAD

**Issue by Norwegian-Sardines** [FamilySearch/GEDCOM#490]
In GEDCOM v5.5.1 the definition for `SOUR.DATA.DATE` was: <ENTRY_RECORDING_DATE>
>The date that this event data was entered into the original source document.

This definition at a minimum is missing from the the current version of GEDCOM v7.0.14

For Source_Citations this date definition plus the date you last visited the website is also be needed.

A new definition for the payload could include both: 
>"For immutable source documents, (i.e. Census, Historical Church Documents) the date represents when this data was entered in the original source document, for variable and subject to change sources (i.e. websites, aggregator documents) the date represents when the data was last visited."

**Comment by tychonievich** [comment]
I think it does have a definition, though I agree it is somewhat roundabout. It is a `g7:DATE`, which is defined as 

> The principal date of the subject of the superstructure. The payload is a [DateValue](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#date).

It's superstructure is a `g7:SOUR-DATA`, which is defined as 

> A structure with no payload used to distinguish a description of something from metadata about it. For example, [SOUR](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#SOUR) and its other substructures describe a source itself, while [SOUR.DATA](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#SOUR-DATA) describes the content of the source.

Ergo, `SOUR`.`DATA`.`DATE` is the principle date of the contents of the source.

I agree that this could be clearer and more direct, and that both 5.5.1's sentence and @Norwegian-Sardines's new suggested text are clearer and more direct and are compatible with the current indirect definition. I personally prefer the 5.5.1 definition as I'm OK with source citations that are preserved in snapshot form and not updated upon a later revisit.
