### ISSUE TITLE
generate-files github workflow files pull requests that are blocked because validate-yaml never runs

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#503]
See https://github.com/orgs/community/discussions/57484 for explanation.

https://github.com/FamilySearch/GEDCOM/blob/main/.github/workflows/generate-files.yml#L72 current uses the GITHUB_TOKEN which is the problem.

The recommended fix seems to be to use a PAT rather than GITHUB_TOKEN.

**Comment by tychonievich** [comment]
As noted in the linked discussion, this can be worked around by closing and then re-opening the blocked PR. I've verified that that workaround unblocks the blocked PRs we had on our various repos.

I'm not very keen on making a PAT and attaching it to the actions [through a GitHub app](https://docs.github.com/en/actions/security-guides/automatic-token-authentication#granting-additional-permissions); I don't have a deep understanding of that process so I might be wrong, but what I do looks to me like it overly ties the workflow to a single user.
