### ISSUE TITLE
PLAC jurisdiction can be larger than a nation

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#512]
Text currently reads:
> The principal place in which the superstructure's subject occurred, represented as a [List] of jurisdictional entities in a sequence from the lowest to the highest jurisdiction, where "jurisdiction" includes units in a political, ecclesiastical, and geographical hierarchies and may include units **as large as a nation** or as specific as a building, farm, or cemetery. As with other lists, the jurisdictions are separated by commas. Any jurisdiction's name that is missing is still accounted for by an empty string in the list.

The "as large as a nation" can be read as saying that's the largest possible jurisdiction.
However there are records that just list continent (e.g., "emigrated to North America"), or ocean.

**Comment by Norwegian-Sardines** [comment]
“Ocean” or “at sea” is very often a burial location, and in one case in my genealogy a birth place!  In early emigration destinations “the Americas” did not always mean the USA.

“from the largest entity, or as…”
