### ISSUE TITLE
ADD <<SOURCE_CITATION>> under INDI.FAMC and INDI.FAMS

### ISSUE THREAD

**Issue by albertemmerich** [FamilySearch/GEDCOM#533]
It is often difficult to get the correct parents or spouses from given data in sources. So in these cases we should document the sources we used to build up these connections very carefully.
However: INDI.FAMC and INDI.FAMS do not allow to put source citations in their substructure, any other event or fact does allow. We should close this gap and add 
```
+2 <<SOURCE_CITATION>>                   {0:M}
```
under INDI.FAMC and INDI.FAMS.

**Comment by Norwegian-Sardines** [comment]
Already discussed in https://github.com/FamilySearch/GEDCOM/issues/494 and elsewhere!

**Comment by albertemmerich** [comment]
Correct, I did not find that when opening the issue. I close it.
