### ISSUE TITLE
EXID.TYPE for BillionGraves.com and WikiTree identifiers

### ISSUE THREAD

**Issue by elyoh** [FamilySearch/GEDCOM#539]
Identifiers for [BillionGraves.com](https://www.billiongraves.com/) and [WikiTrees](https://www.wikitree.com/) are included in some GEDCOM files using extension tags (`_BGRAVE` `_BGLINK` `_WIKITREE` `_WIKILINK`).

This request is for the following EXID types to be registered to support greater compatibility (as was done in #261).

Description | Type | Example | Reference
-- | -- | -- | --
BillionGraves Cemetery ID | https://www.billiongraves.com/cemetery/name/ | George Washington Memorial Park [https://billiongraves.com/cemetery/name/68270](https://billiongraves.com/cemetery/name/68270) | https://billiongraves.com/search/cemetery
BillionGraves Grave ID | https://www.billiongraves.com/grave/name/ | George Washington [https://billiongraves.com/grave/name/361654](https://billiongraves.com/grave/name/361654) | https://billiongraves.com/search
WikiTree Person ID | https://www.wikitree.com/wiki/ | George Washington [https://www.wikitree.com/wiki/Washington-2114](https://www.wikitree.com/wiki/Washington-2114) | https://www.wikitree.com/wiki/Help:WikiTree_ID

**Comment by dthaler** [comment]
@elyoh thanks for the corrections in comments!  reopening this issue so that the updated URLs can be done in a PR before this is considered fixed.

**Comment by dthaler** [comment]
Fixed in PR #543
