### ISSUE TITLE
HEAD.LANG and untagged payloads

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#55]
5.5.1 defined HEAD.LANG as "The human language in which the data in the transmission is normally read or written.  It is used primarily by programs to select language-specific sorting sequences and phonetic name matching algorithms."

7.0 clarified that as "a default value for the rest of the document" and "The language in which the `Text`-typed payloads of all structures in the document appear, except as superseded by a `g7:LANG`."

However, neither is accurate in practice. There are many `<Text>`-payload structures that do not admit a `g7:LANG` substructure, and there is no reason to believe they all have the same human language. As written, merging files with different HEAD.LANG is impossible.

In the 2021-09-14 steering committee meeting, this was identified as an error in the spec, and one to be fixed by a patch as soon as possible. This is a patch under the provision "If there is an ambiguity or contradiction in the specification, it will be resolved in a patch version unless it is known that implementations interpreted the spec differently and that clarifying the intended meaning would cause incompatibilities between those implementations."

**Comment by tychonievich** [comment]
Options:
1. We could keep the current text but say the language tag `und` should be used unless all `<Text>` payloads without a `g7:LANG` substructure are in the same language
2. Redefine `g7:HEAD-LANG` to be something vague like a "language hint" instead of the more formal language of untagged `<Text>` payloads
3. Add some kind of placeholder text like "This structure indicates a language used in some subset of the rest of the dataset. However, the current specification does not have enough data to fully identify the language of all Text payloads. Once a future version defines how to specify the language of every Text payload, `g7:HEAD-LANG` will be a default language tag.

Preferences? Other options?

**Comment by fisharebest** [comment]
I prefer 1.

Since `HEAD.LANG` is optional, perhaps state that if it missing, then a GEDCOM-reader should assume `und`.

**Comment by dthaler** [comment]
Albert's technical points convinced me that option 2 is the best path, since "unless all <Text> payloads without a g7:LANG substructure are in the same language" is not implementable.

[RFC 6365](https://datatracker.ietf.org/doc/html/rfc6365#page-29) says:

>    language identification
> 
>       Specification of the human language used for a string of text.
>       <RFC6365>
> 
>       Some protocols (such as MIME and HTTP) allow text that is meant
>       for machine processing to be identified with the language used in
>       the text.  Such identification is important for machine processing
>       of the text, such as by systems that render the text by speaking
>       it.  Language identification is also called "language tagging".
>       The IETF "LTRU" standards [RFC5646] and [RFC4647] provide a
>       comprehensive model for language identification.

[RFC 5646](https://datatracker.ietf.org/doc/html/rfc5646#section-1) elaborates:

>    The language of an information item or a user's language preferences
>    often need to be identified so that appropriate processing can be
>    applied.  For example, the user's language preferences in a Web
>    browser can be used to select Web pages appropriately.  Language
>    information can also be used to select among tools (such as
>    dictionaries) to assist in the processing or understanding of content
>    in different languages.  Knowledge about the particular language used
>    by some piece of information content might be useful or even required
>    by some types of processing, for example, spell-checking, computer-
>    synthesized speech, Braille transcription, or high-quality print
>    renderings.

Note the use of the word "preference" in the text above, which is consistent with option 2.

**Comment by tychonievich** [comment]
In principle I'm OK with option 2, but I don't know how to make it concrete. A user's language preference (which is what RFC5646 refers to) is stored in GEDCOM in the `g7:SUBM-LANG` structure. What does it mean to have a *file*'s preferred language? Even with the more vague wording, how do we recommend picking `g7:HEAD-LANG`? The first (and hence most-preferred) `g7:SUBM-LANG` of the most recent user to edit the file?

My best current guess at text for option 2 is "A language hint. If an application wishes to process a piece of text in a language-specific way but cannot identify the language of the text, either by the payload of an appropriate `g7:LANG` or a language detection heuristic, then the `g7:HEAD-LANG` provides a suggested fallback language." But I'm not very happy with that.

 

> since "unless all payloads without a g7:LANG substructure are in the same language" is not implementable.

It could be implemented by the following algorithm:

1. When creating a new file, pick an initial `g7:HEAD-LANG`
2. Each time a user enters or edits any text, ask them if the text matches the current `g7:HEAD-LANG` payload
3. If not (or if they don't respond), remove `g7:HEAD-LANG` (or equivalently replace its payload with `und`, but that's not recommended)

That said, it is possible that this algorithm would result in `g7:HEAD-LANG` being removed more often than not.

**Comment by dthaler** [comment]
> In principle I'm OK with option 2, but I don't know how to make it concrete. A user's language preference (which is what RFC5646 refers to) is stored in GEDCOM in the `g7:SUBM-LANG` structure. What does it mean to have a _file_'s preferred language? Even with the more vague wording, how do we recommend picking `g7:HEAD-LANG`? The first (and hence most-preferred) `g7:SUBM-LANG` of the most recent user to edit the file?
> 
> My best current guess at text for option 2 is "A language hint. If an application wishes to process a piece of text in a language-specific way but cannot identify the language of the text, either by the payload of an appropriate `g7:LANG` or a language detection heuristic, then the `g7:HEAD-LANG` provides a suggested fallback language." But I'm not very happy with that.

I'd expect that applications would want to fill in the default language based on the User Locale (see [User Locale](https://docs.microsoft.com/en-us/globalization/locale/user-locale) for Windows, but equivalents exist on other OS's) in use by the [Input Method Editor (IME)](https://en.wikipedia.org/wiki/Input_method). 

> > since "unless all payloads without a g7:LANG substructure are in the same language" is not implementable.
> 
> It could be implemented by the following algorithm:
> 
> 1. When creating a new file, pick an initial `g7:HEAD-LANG`
> 2. Each time a user enters or edits any text, ask them if the text matches the current `g7:HEAD-LANG` payload

Someone (Albert?) pointed out that not all text comes from the user per se.  As one example, you can import another GEDCOM into your database.

> That said, it is possible that this algorithm would result in `g7:HEAD-LANG` being removed more often than not.

Right, it essentially becomes absent in almost all practical cases, I would think, if you tried that algorithm.  (I wouldn't be in favor of that personally.)
