### ISSUE TITLE
Request to update/create tags for software specifically in the HEAD

### ISSUE THREAD

**Issue by rhires** [FamilySearch/GEDCOM#550]
Proposal to create new tags for the HEADER for the sake of clarity and specificity. 

`n HEAD.SOUR.SOFTWARE` the name of the source software that created this transmission/GEDCOM file. This would replace `DATA` in this context. 
`+1 ENTI` - to replace `CORP` - the entity that created the software that created this transmission - this removes ambiguity as an entity could be a person, group of people, an open source project, or a company/corporation. And it doesn't look like a "corporation" only. 
`+1 NAME` - name of the software itself. 
`+1 DLOC` - download location of the software (usually a URL)
`+2 DNAM` - name of the download website if different from that of the software creator - e.g., GitHub, Sourceforge, Apple App Store
`+1 EWEB `- entity website, different from the software download location, that provides information on the entity itself that created the software
`+1 SVER` - Software version of the software that produced the transmission
`+1 SLOC` - software source code repository location if the software is open source

Other +1 tags might include "MEDIA" in the situation where a software package is on some other form of media, such as a CD ROM, or a thumbdrive (but I don't see a real need for this, since CD ROM is rapidly becoming obsolete, and no one distributes software except through internet. Physical media for distributing software is no longer used.)

**Comment by Norwegian-Sardines** [comment]
Some of the tag changes are not needed!  Changing the following does not make it better!

`HEADER.SOUR` = An identifier for the product producing this dataset.  Describes the originating software.  <= This is the software
`HEAD.SOUR.VER` = version level assigned to the associated product.
`HEAD.SOUR.CORP.WWW` = entity website

We could change the `SOUR.CORP` name, or just read the definition of the field:
>The name of the business, corporation, or person that produced or commissioned the product.  

I not sure if we need `DLOC` and `SLOC` together, one of the other would be ok.  `DNAM` in my mind is overkill since the name is most likely in the DLOC/SLOC.

>Physical media for distributing software is no longer used.  

I don't see a MEDIA tag in the HEADER! 

Where are we talking about distributing software"? A GEDCOM can be sent via DVD from me to you.  The HEADER describes the transmitted GEDCOM, we know the media because we have it ether on our computer or in our hand (DVD, thumb drive).

**Comment by Norwegian-Sardines** [comment]
Even if software was still distributed via CD, or thumb drive, I don’t think that knowing the way the software was delivered to the GEDCOM producer is important!  All that is important is the name of the software, the software developer and contact information, and version of the software.  

Hopefully the developer used proper versioning nomenclature. If an open source software program is used, but modified by a third party my hope is that the GEDCOM HEADER would be updated to include a new SOUR value with a URI pointing at the 3rd party not the original open source creator.  This gets a little crazy when commercials software allows API access to their database which could change the input, storage and GEDCOM produced.  Most API programmers will not go thru the process of actually creating a new HEADER.SOUR for their output.

The reality is that most of the information in the HEADER is not required.  The value of the SOUR section helps the receiver to potentially know the dialect of GEDCOM used, but it is not 100% accurate.  I have seen in the wild a GEDCOM that states a version of GEDCOM but contains data structures for deprecated tags!

**Comment by tychonievich** [comment]
Discussed in steering committee 1 OCT 2024

- We agree that it is useful to have information about the software that generated the file. The current HEAD.SOUR, HEAD.SOUR.NAME, HEAD.SOUR.VERS, HEAD.SOUR.CORP, and HEAD.SOUR.CORP.WWW structures  seem to provide this information adequately to find more about the software online (possibly including on digital archives of no-longer-present websites).
- We agree that some of the added structures @rhires proposes are not currently in the HEAD.SOUR, while others are renamings of existing structures as pointed out by @Norwegian-Sardines. Renamings can't happen before a major version, so the current names will remain at least through all version 7.x.
- We failed to identify use cases that the additional information proposed here would enable which are not enabled by the current information. @rhires could you point out some uses that the new data would enable?

**Comment by rhires** [comment]
@tychonievich I similarly don't have specific use cases that the additional information would enable. I wish I did. The only thing I can think of is that software authors/companies might have useful information to include for their own purposes. 

GEDCOM files have dialects; having a place to note the dialect might be useful, but I'm not addressing your question. It might be useful for marketing purposes to have these extra tags, but that's me just guessing. I really don't know.

**Comment by Norwegian-Sardines** [comment]
GEDCOM files have dialects; having a place to note the dialect might be useful, but I'm not addressing your question. It might be useful for marketing purposes to have these extra tags, but that's me just guessing. I really don't know.

The dialect of the GEDCOM (we are not talking about a human dialect) is very important.  Knowing the dialect used will help figure out what a tag that does not exist (either an extension or not) in the Standard might mean.  This is less important if they documented their extensions with a URI link, but my suspicion is that they will not and some GEDCOMs are produced via open source changes that will may even be less available or accurate.

**Comment by dthaler** [comment]
The `HEAD`.`SOUR` payload (typically together with the `HEAD`.`SOUR`.`VERS` payload) identifies the dialect.  It doesn't define any details about the dialect, but it does serve as an identifier of it.  Information about the dialect requires either registered extensions, or the ability to find some document by the software creator.  `HEAD`.`SOUR`.`CORP`.`WWW`, if present, identifies a website that might have such information on it, and either way a web search on the `HEAD`.`SOUR` payload and/or the `HEAD`.`SOUR`.`NAME` payload, can sometimes find information from the creator or even a third party.  I don't think the other tags suggested above make it significantly easier to locate such information, and such information may not even exist anywhere online.  Hence, Luther's response seems right to me, but let me know if I'm missing something.

**Comment by dthaler** [comment]
Discussion during GEDCOM Steering Committee 8 OCT 2024:
Since there are not specific use cases yet, we are closing this for now.  If use cases arise in the future, this issue can be reopened.
