### ISSUE TITLE
Update the SUBM tag in the HEAD to allow for Previous contributors

### ISSUE THREAD

**Issue by rhires** [FamilySearch/GEDCOM#551]
The SUBM tag assumes that all the records "to be contributed by the submitter referenced in the [HEAD](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#HEAD), are by the same person", but what I would like is if I can show in this tag in the HEAD that it's really a series of docs put together in one place by me (as the most recent submitter), but I also wish to show that, say, "the line from person A came from submitter A, and the line for person B came from submitter B", or that the submitter previous to me, where I got ALL the data, is from a single source, and that I added to it. It would be useful for traceability. 

Example: if I got a GEDCOM from my cousin, that I then added to/extended, I want to be able to add that person's contribution. 

n SUBM
+1 NAME
<this is the new idea>
+1 PCON - previous contributor {0:M} 
+2 NAME
+2 - other relevant details
+2 DATE - this is when I added the other contribution to the overall data
</>

I'm unsure of how to identify what the overall contribution was, except maybe a XREF to other SUBM data elsewhere in the GEDCOM.

**Comment by Norwegian-Sardines** [comment]
The SUBM tag is used in multiple places.

- HEADER
- Family_Record
- Individual_Record

If some other individual or entity provided you with (contributed) the information about a particular person or family you would include the SUBM tag and the subsequent Submitter_Record.

If you received a GEDCOM from another person that added the individual or family to your database, I would assume the appropriate action would be to either automatically add the submitter record connection for that contributor to the `INDI.SUBM` tag.  I would also think that the GEDCOM already provided the Submitter_Record for their GEDCOM payload, but the reality is they probably did not!

You on the other hand would enter your submitter information into a Submitter_Record and link to it in the `GEDCOM.HEADER` when you export your GEDCOM!

**I personally would like to see the SUBM tag added to the Multimedia_Record for people the supplied media to me in their GEDCOM transmittal to me or if they sent me an image I'm using in my GEDCOM.**

I would also Like to see a subtag to the SUBM tag for DATE to identify when this Individual or Family was added to my GEDCOM, a submitter could transmit a GEDCOM to me multiple time with updates and I'd like to track which transmission added the Individual or Family:
n SUBM @<XREF:SUBM>@
+1 DATE <DateExact>

**Comment by tychonievich** [comment]
Discussed in steering committee 1 OCT 2024
- We think that the recommendation to use INDI.SUBM and FAM.SUBM from @Norwegian-Sardines answers the question "I also wish to show that, say, "the line from person A came from submitter A, and the line for person B came from submitter B"."
- We like @Norwegian-Sardines suggestion to add OBJE.SUBM; this has been proposed before and is tracked in #532 
- We agree that there are cases where entire GEDCOM files are prepared by one person, then modified by a second person, then exported, and that some (but not all) users wish to track this sequence of file owners. We think that this can be stored in the GEDCOM file by listing the SUBM for each INDI/FAM; it's not clear to us what additional utility would be added by putting the full set of SUBM that have ever contributed to the file in the HEAD as well.

We do not see additional action items, so we are closing this issue. If we have missed something, feel free to post a follow-up and reopen it.
