### ISSUE TITLE
Wrong use of quote marks in one of the YAML files?

### ISSUE THREAD

**Issue by stevespages** [FamilySearch/GEDCOM#558]
The standard tag In the YAML file at https://gedcom.io/terms/v7/NO is quoted with single quote marks ie. it is 'NO' instead of NO. I think this might be a mistake and it is causing me a problem with some code I am writing. Other standar tags are not quoted.

**Comment by dthaler** [comment]
Looks like it's a bug in the script that creates the YAML files... probably in this line:
https://github.com/FamilySearch/GEDCOM/blob/main/build/uri-def.py#L399

**Comment by tychonievich** [comment]
This is by design. YAML has many ways of spelling the boolean value `false`, including `NO`; the quotes are needed here to make `NO` be a string instead.

**Comment by stevespages** [comment]
I would like to expand on why it seems to be a problem for me. When people use the standard tag in a gedcom file they would probably use NO and not 'NO' (for example in the file maximal70.ged on the gedcom.io site). However, if in the YAML document for NO, it specifies the standard tag as 'NO' then a literal interpretation would be that the tag should be used with the quotes in gedcom files.

I am extracting the YAML files into my gedcom parser so it fails with NO as it is expecting 'NO'. I could of course get my program to strip quotes from the standard tag from the YAML files if necessary.
