### ISSUE TITLE
Is maximal70.ged valid GEDCOM 7?

### ISSUE THREAD

**Issue by stevespages** [FamilySearch/GEDCOM#561]
I have been using the maximal70.ged file at https://gedcom.io/tools/ to test the application I am building and have been assuming it is valid GEDCOM 7.

I am now worried it is not valid as I have found that there is a substructure of record-INDI which has a tag of NAME (and therefore must have a URI of g7:INDI-NAME) with the payload value AKA.

AKA would not seem to satisfy the description of <PersonalName> which should be the payload of a g7:INDI-NAME structure. AKA is a member of the enumeration set which is permitted as the payload for the g7:NAME-TYPE structure.

My feeling is that maximal70.ged is therefore not valid GEDCOM 7 but I would like clarification on this point.

I would like a valid gedcom file for testing my application which also is extensive like the maximal70.ged if you could suggest one.

**Comment by dthaler** [comment]
maximal70.ged has:
```gedcom
1 NAME Aka
2 TYPE AKA
```
So AKA (all caps) is the payload for the g7:NAME-TYPE structure.

"Aka" is a string in the payload for the g7:INDI-NAME structure which is defined as `<PersonalName>` which is defined in [section 2.8](https://gedcom.io/specifications/FamilySearchGEDCOMv7.html#cb26-1) as:
```abnf
PersonalName = nameStr
             / [nameStr] "/" [nameStr] "/" [nameStr]

nameChar     = %x20-2E / %x30-10FFFF  ; any but '/' and '\t'
nameStr      = 1*nameChar
```
and "Aka" is a legal string that matches the `nameStr` pattern, so maximal70.ged is valid GEDCOM 7.
There are several validators listed at https://gedcom.io/tools/#v70-parsers that can be used to check validity (barring any bugs in the validators themselves).

**Comment by stevespages** [comment]
It seems to me that if you believe that someone's name is "AKA" or "Immigrant Name" then it is perfectly to intend those strings to be used as the payload for the g7:NAME-TYPE structure. However, to intend to use those strings as payloads for that structure when you believe them to be payloads for a different structure is an invalid use of the GEDCOM spec. It is certainly a misleading and unhelpful one.

**Comment by dthaler** [comment]
Discussion in GEDCOM Steering Committee:
* The file is valid GEDCOM 7 but indeed may be confusing if the raw file is read by a human
* The committee suggested that we add a `HEAD`.`NOTE` explaining more.  Luther took the action item to file a pull request.

**Comment by stevespages** [comment]
That is good. Thanks.

**Comment by dthaler** [comment]
Fixed in the GEDCOM.io repository in https://github.com/FamilySearch/GEDCOM.io/pull/206
