### ISSUE TITLE
Merge exid-types.json with gedcom-registries

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#569]
exid-types.json predates gedcom-registries, and has some overlap with it (in particular, it duplicates the semantic purpose of https://github.com/FamilySearch/GEDCOM-registries/tree/main/uri/exid-types). We should merge these two to avoid duplicate information, probably keeping the registries because it is more versatile.

**Comment by dthaler** [comment]
exid-types has: label, type, description, contact, change-controller, and reference.

These can be mapped to https://gedcom.io/terms/format fields as follows:

* label -> label
* type -> uri
* description -> specification
* contact -> contact
* change-controller ("FamilySearch" for AFN/RIN/RFN) ->??? no current field
* reference -> ??? no current field

**Comment by dthaler** [comment]
Filed https://github.com/FamilySearch/GEDCOM.io/issues/220 in GEDCOM.io regarding change-controller and reference.

**Comment by tychonievich** [comment]
Adding one entry:

* reference -> documentation

(see https://gedcom.io/terms/format)

**Comment by dthaler** [comment]
https://github.com/FamilySearch/GEDCOM-registries/pull/102 added the data from exid-types.json to gedcom-registries.  exid-types.json can now be deleted.

**Comment by chronoplexsoftware** [comment]
The removal of the exid-types.json has left a number broken references in the documentation which need to be corrected.

https://github.com/FamilySearch/GEDCOM/blob/5c2eb6046972c21abd877a8b8ed5d2447ed5b260/extracted-files/tags/EXID-TYPE#L22C1-L36C18

https://gedcom.io/_pages/exid-type/
