### ISSUE TITLE
Need for GEDCOM metadata

### ISSUE THREAD

**Issue by jl5000** [FamilySearch/GEDCOM#577]
Re: #533 and #498

I'm at risk of opening a can of worms here, but the discussions above and my own struggles with the logistics and inefficiency of plastering my files with duplicate source citations is screaming at me that the underlying data structure is... unhelpful.

We have several structures that could theoretically be applied to every line of a GEDCOM record (with some exceptions) creating a matrix structure... and these can generally be described as "metadata". RESN, SOUR, and (S) NOTE immediately spring to mind but there could be others. 

I think GEDCOM v8 would be an opportune time to seriously consider how to deal with this, and whether it's time to step into 2 dimensions (or rather formalise the existing 2 dimensions).

**Comment by tychonievich** [comment]
Thanks for the idea! During the 7.0.0 specification process I proposed a similar idea and even produced a draft spec that had "universal substructures" for these kinds of structures that make sense in many places. That was circulated to the people listed in the "contributors" section of 7.0.0 and many of them were unhappy about the need that implied to restructure their software. For those like me that have a dynamic linked data backend, having universal substructures seemed like a simple addition that made my code simpler, not more complicated. But for those who had relational databases or separate classes for each structure type, adding this meant making hundreds of changes with limited obvious utility. Thus, we removed that idea from 7.0.0 before it was published.

Making this change would be quite a large change from most software's perspective, in many cases requiring a redesign of their basic data model. I think *technically* it could be a minor version as it's only adding new places where data could appear, I doubt we'd do it before a major version.

**Comment by tychonievich** [comment]
> Luther, What database engine do you use in your desktop application?

I used to use OrientDB, which worked well but was more setup than I really needed so I switched to an custom in-memory graph backed by an append-only replay log.

**Comment by Norwegian-Sardines** [comment]
Not many commercial desktop applications are going to have anything beyond an SQL based DB Engine like SQLite.  I’m running MariaDB on a server that keeps the raw GEDCOM as is!  Most desktop apps convert the GEDCOM into more traditional table based data which drops a lot of the lesser used tags!

**Comment by Norwegian-Sardines** [comment]
As I see it what you are proposing as a data transfer protocol would require an object oriented model.  As I indicated most software can not use an object oriented database and therefore will drop most data provided in your model! How would you propose a new standard that can’t be used by applications that use the data?

**Comment by Norwegian-Sardines** [comment]
I don’t understand, maybe I just dumb, but how do you add attributes to a field in a flat file transmission?  Expand on your proposal with something concrete!
