### ISSUE TITLE
Missing URI guidance for EXID.TYPE

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#63]
EXID was created as a replacement for AFN, RFN, RIN, etc., but no guidance exists on how to represent/distinguish their values in GEDCOM 7.   The EXID.TYPE just says to use a URI, ideally a URL that the value can be added to as a suffix.
However, what is the appropriate URI for an AFN for example?

https://github.com/gedcom7code/c-converter/blob/main/pipeline/exid.c#L4 says:
```
 * Change three application-specific IDs to EXID
 * 
 * RFN X -> EXID X + TYPE gedcom551:RFN
 * RIN X -> EXID X + TYPE gedcom551:RIN/<HEAD.SOUR>
 * AFN X -> EXID X + TYPE gedcom551:AFN
```

However, the comment is wrong, and the https://github.com/gedcom7code/c-converter code instead converts them as follows:
```
* RFN X -> EXID X + TYPE ged551:RFN
* RIN X -> EXID X + TYPE ged551:<payload of HEAD.SOUR>
* AFN X -> EXID X + TYPE ged551:AFN
```

Furthermore,

1) neither gedcom551: nor ged551: are registered URI schemes at https://www.iana.org/assignments/uri-schemes/uri-schemes.xhtml and so this is squatting on an unregistered value
2) the GEDCOM 7 spec does not say to use these values, so every application might use a completely different URI, preventing interoperability that formerly existed with GEDCOM 5.5.1 by recognizing the AFN tag.

**Comment by tychonievich** [comment]
https://gedcom.io/migrate/#afn-rfn-rin uses

- `AFN x` → `EXID x` + `TYPE https://www.familysearch.org/wiki/en/Ancestral_File`
- `RIN x` → `REFN x` + `TYPE `"my system"
- `RFN x:y` → `EXID y` + `TYPE https://gedcom.io/terms/v7/RFN#x`

Note that it does not define what URL "my system" is, <https://gedcom.io/terms/v7/RFN> is a dead link, and `REFN` is not a good match for `RIN`.

**Comment by tychonievich** [comment]
For AFN, I like the migration guide:

- AFN x → EXID x + TYPE https://www.familysearch.org/wiki/en/Ancestral_File

For RFN, I tihnk the migration guide is on the right track; we just need to define a usable URL:

- RFN x:y → EXID y + TYPE \<some URL we create>#x
    
    At the URL, we'd serve something like
   
    > GEDCOM 5 through 5.5.1 had a notion of a "registered resource identifier". The registration process was never widely followed and ceased being used in the early 2000s. The URL you have visited is a placeholder for such a "registered resource identifier", which may or may not have been registered and hence may or may not be a unique resource identifier.

I don't know what to do with RIN. I'm not sure what purpose it served in previous versions. As far as I can tell, it was something like a row ID in a database table, but which database is not identifiable by any combination of other fields in the standard. (HEAD.SOUR + HEAD.FILE might be enough for an online tool SOUR, but not for a desktop tool). I don't think we can treat RIN as EXID at all. REFN doesn't make much sense either, as it's supposed to be user-visible and user-editable.

My instinct is to change it to discard RIN entirely, but I suppose it is useful if you know (though some non-standard source) what database the file was generated by, so discarding it is probably not correct either. Maybe turn it into an extension tag?

**Comment by dthaler** [comment]
> * `RIN x` → `REFN x` + `TYPE `"my system"
> 
> Note that it does not define what URL "my system" is

```
n REFN <Special> {1:1} g7:REFN
+1 TYPE <Text> {0:1} g7:TYPE
```
uses g7:TYPE which is not a URL.  It's just "a descriptive word or phrase" with no uniqueness guarantees or way to map it to any meaning, so literally "TYPE my system" 
would be legal, as far as I can tell.  Let me know if I'm missing something.

**Comment by dthaler** [comment]
@tychonievich Should this issue be closed now?
