### ISSUE TITLE
Correct email address for GEDCOM spec maintenance & discussion?

### ISSUE THREAD

**Issue by dthaler** [FamilySearch/GEDCOM#65]
- The GEDCOM 7 and 2019 final GEDCOM 5.5.1 spec title pages say: **GEDCOM@ChurchOfJesusChrist.org**
- The 1999 DRAFT GEDCOM 5.5.1 spec, the 5.5, 5.4, and 5.3 specs all say: **gedcom@gedcom.org**
- https://gedcom.io/community/  says: **GEDCOM@familysearch.org**
- And then there's: https://groups.google.com/g/gedcomgeneral
- We're not using https://github.com/FamilySearch/GEDCOM/discussions but we could, which would make it easier to file issues based on discussion.

**Comment by dthaler** [comment]
https://github.com/FamilySearch/GEDCOM.io/pull/12 already added a note about the correct email contact (GEDCOM@familysearch.org) for older spec versions.

https://github.com/FamilySearch/GEDCOM/discussions/75 tracks moving from the google group to github discussions.

The last remaining issue not tracked by any other issue is the first bullet.

**Comment by tychonievich** [comment]
v7.0.6 updated the email address on https://gedcom.io/specifications/FamilySearchGEDCOMv7.html; the old email addresses no longer appear anywhere on gedcom.io or this repository.
