### ISSUE TITLE
Does using URIs make GEDCOM less archival?

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#69]
(originally posted by @emyoulation on #41; copied verbatim to its own issue)

I just ran into something that might need to be an archival consideration for posterity.

When trying to transfer some old XML files to a modern package. I discovered that some DTD and scheme URIs inside the file were bad: they had suffered linkrot or had been clobbered. As a result, the reader was not able to parse some of the chunks. (In this case, the chunks were metadata for the 2016 retired & 2019 deprecated Picasa face recognition for photos.)

Should some thought be given to specifying how to handle this so that our files maintain long-term integrity?

Maybe have a fallback specification for linkrot affected  external references? And some sort of override for clobbered external references.

Superficially, this includes things in the specification like the "http://www.apache.org/licenses/LICENSE-2.0" external reference. In 50 years, will the Apache domain exist? Will we still be using nameservers that can resolve it?

Perhaps there should be an internally redundant Archival GEDCOM format that archives this specification with the the data file?

Reference v7.0.2 page 6 of 96: section "URIs and Prefix Notation"

What happens if the following domain is hacked and the schema is clobbered with mangled structure that RickRolls XML reader applications to a malicious schema?
http://www.w3.org/2001/XMLSchema#

_Originally posted by @emyoulation in https://github.com/FamilySearch/GEDCOM/issues/41#issuecomment-940066677_

**Comment by dthaler** [comment]
I believe the wayback machine solves the obsolete embedded links problem by having the text show the original text, but the embedded link is modified to go to a backup location.

Similarly IETF RFCs are immutable and may have obsolete links, but RFC 7990 explains how the RFC editor can solve this for new RFCs.   The immutable format for new RFCs is XML.  Automated tooling generates presentation formats like HTML, PDF-A (a great format for archival), etc.   The tooling can change over time, so the presentation format might include a link to errata, or things like the wayback machine does, etc.

So while we can't change the text of older GEDCOM versions, we could create presentation formats like above that augments it either with clickable links, or margin notes or whatever, as long as it's clear what is the immutable part/format and what is the presentation.  

For example https://www.rfc-editor.org/info/rfc7990 discusses the metadata such as how to cite the doc from other docs, and links to the actual document, https://www.rfc-editor.org/rfc/rfc7990.html contains the immutable content plus clickable links inline, plus a non-immutable header in gray.
