### ISSUE TITLE
Deprecate / remove support for UTF-16 / CHAR UNICODE

### ISSUE THREAD

**Issue by fisharebest** [FamilySearch/GEDCOM#76]
To my knowledge, no application has created GEDCOM files using `1 CHAR UNICODE` /  `UTF-16`.

I have only encountered some hand-crafted test files.

Since `UTF-8` and `UNICODE` support was first added to the GEDCOM spec, `UTF-8` has emerged as a de-facto standard.

It is trivial to create a program/script to convert a `UNICODE` GEDCOM file into a `UTF-8` one.  (`UTF-16` is a strict subset of `UTF-8`).

I'd like to propose that we mark `UTF-16` as deprecated.  e.g.

> Support for encodings other than `UTF-8` are deprecated, and will be removed in 8.0.0

The only valid value for `HEAD.CHAR` is now `UTF-8`.  We can remove it.

This would help with #5

**Comment by tychonievich** [comment]
For context:
- FamilySearch GEDCOM 7.0 is UTF-8 only.
- We are not planning to edit the content of any previous GEDCOM specifications
- But we are discussing how to specify (roughly) "all GEDCOM versions ever" as part of [the media type specification](https://github.com/FamilySearch/GEDCOM/blob/main/version-detection/version-detection.md). Whether deprecation is the right tool for that document or not is not clear to me.
