### ISSUE TITLE
What is recommended approach to remarriage

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#85]
The posted sample file <https://gedcom.io/testfiles/gedcom70/remarriage.ged> handles a remarriage as one FAM per MARR; the relevant piece is

```gedcom
0 @F1@ FAM
1 HUSB @I1@
1 WIFE @I2@
1 MARR
2 DATE 1 APR 1911
1 DIV 
2 DATE 2 MAY 1912
0 @F3@ FAM
1 HUSB @I1@
1 WIFE @I2@
1 MARR
2 DATE 4 JUL 1914
```

Peter argues in <https://groups.google.com/g/gedcomgeneral/c/NsM8DV033DM> that we should instead recommend multiple MARR in a single FAM:

```gedcom
0 @F1@ FAM
1 HUSB @I1@
1 WIFE @I2@
1 MARR
2 DATE 1 APR 1911
1 DIV 
2 DATE 2 MAY 1912
1 MARR
2 DATE 4 JUL 1914
```

I don't have strong leanings on this, though on the whole I am inclined to agree with Peter that one FAM is better than two in this case. Either way, I think we should include an explicit mention of this ambiguity in the spec: either recommending one or the other or providing some rationale for not recommending either.

**Comment by dthaler** [comment]
Here's another case.
* The marriage, divorce, and remarriage between A and B have no known dates, they were just known to happen (`MARR Y').   I am not sure this can be represented accurately with only one FAM, since you cannot even use "BEF" or "AFT" dates to force an order saying that a MARR happened after a DIV.

**Comment by albertemmerich** [comment]
I do not accept the last comment. We have SDATE in GEDCOM 7 and by that are able to sort with estimated dates.

**Comment by tychonievich** [comment]
Discussed 2021-11-16
1. We should be clear that both are permitted in the spec and that applications should not change one of these solutions into the other

We should add a NOTE about this complexity, including such ideas as

- single FAM with two MARR with distinct dates might represent uncertainty about dates, or might represent remarriage
- pair of FAM with same spouses might represent distinct unions of same couple, or might be the result of merging multiple files
- single FAM vs pair of FAMs might be a user visualization hint to allow the system to display the remarriage in different ways, or might be the result of different tools' default representations of remarriage

We should also add another example file that does the other kind of remarriage.

We expect two pull requests:
1. on this repo, adding a note to the spec
2. on the gedcom.io repo, adding a second example file

**Comment by tychonievich** [comment]
I didn't mean to make  5ba9977  a commit; I meant for it to be a pull request. Sorry!

**Comment by djhenderson** [comment]
The definition of GEDCOM should not be biased by and religious, legal/civil or cultural practices; it must allow the author to record their conclusions.

There are several scenarios where the same two individuals can have multiple marriages. I have four such in my own family tree.

- I have a couple who were married in Scotland, at the groom's parents' parish and also at the bride's parents' parish. This is one FAM record.

- I have a couple who were married in a civil ceremony, and were later married in a religious ceremony. There were no children prior to the religious marriage. This is one FAM record.

- I have a couple who were married, and had several children, and then divorced. Much later they remarried, but subsequently separated. I would consider this two FAM records.

- I have a couple who cohabited for many years, had some children, and later married in a civil ceremony. I would consider this one FAM record.

I strongly believe both the one FAM and two or more FAM scenarios must be supported on GEDCOM, with remarks to the effect that both are acceptable based on the author's best conclusions. Software that processes GEDCOM must never attempt to reinterpret the author's conclusions.
