### ISSUE TITLE
Trailing spaces and empty payloads

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#91]
This issue originally came up in #81

We have

> ```abnf
> Line = Level D [Xref D] Tag [D LineVal] EOL
> ```

which would mean that 

- an empty-string `NOTE` would be encoded "`1 NOTE `" with a trailing space
- a no-payload `CHAN` would be "`1 CHAN`" without a trailing space
- a no-payload `MARR` would be "`1 MARR`" without a trailing space, because of the metasyntax definition 
  > `[`text`|<NULL>]` means the payload is optional but if present must be the given text.
  
  i.e., the empty string is not a valid payload for `[Y|<NULL>]` but a missing payload is

We also have 

> Empty payloads and missing payloads are considered equivalent. The remainder of this document uses “payload” as shorthand for “non-empty payload”.

which suggests that this distinction between no-payload and empty-payload is not meaningful, despite being present in the spec.

The question raised, but not answered, in #81 is (a) should the spec provide a recommendation on the use of trailing spaces with empty payloads and (b) if so, what should it be?

**Comment by dthaler** [comment]
Hmm.  The spec says:

```
Line = Level D [Xref D] Tag [D LineVal] EOL
LineVal = pointer / lineStr
nonAt = %x09 / %x20-3F / %x41-10FFFF ; non-EOL, non-@
lineStr = (nonAt / atsign atsign) *nonEOL ; leading @ doubled
```

So the ABNF does not permit LineVal to be empty, the space must be followed by an atsign or nonAt character.

**Comment by tychonievich** [comment]
Need to clarify that the way to encode the empty string payload is to not have a `LineVal`
