### ISSUE TITLE
Should NOTE.EXID be handled by extension instead of by SNOTE?

### ISSUE THREAD

**Issue by tychonievich** [FamilySearch/GEDCOM#98]
Issue #64 observed that NOTE cannot have an identifier structure, but SNOTE can.

PR #72 added permission for SNOTE to be used when not shared to obtain access to identifiers.

I think PR #72 is confusing the distinction between NOTE and SNOTE and should be rolled back before we release 7.0.6. Instead, I propose adding a non-normative note like

> Note — `SNOTE` allows an `IDENTIFIER_STRUCTURE` substructure, but `NOTE` does not. Conversations are ongoing about changing this in a future version of the specification. Using the current specification, identifiers can be added to `NOTE`s (and other structures) using a [documented extension tag](#extension-tags) by including the following in the header:
>
> ```gedcom
> 1 SCHEMA
> 2 TAG _EXID https://gedcom.io/terms/v7/EXID
> 2 TAG _REFN https://gedcom.io/terms/v7/REFN
> 2 TAG _UID https://gedcom.io/terms/v7/UID
> ```
>
> and using the extension tags like so:
>
> ```gedcom
> 1 NOTE Example
> 2 _EXID external identifier
> 3 TYPE http://example.com/note/identifiers
> 2 _REFN Example note 1
> 2 _UID 7913f642-c2ff-4371-ab3d-1c8d3ffe6663
> ```

**Comment by dthaler** [comment]
FWIW, I like this approach.

**Comment by albertemmerich** [comment]
As with all extensions: Only some of the applications will support them. By this the danger of losses of data increases when exchanging GEDCOM, whenever we use extensions.
In this case I prefer to use SNOTE record, as this is the way in GEDCOM 7.0 to transfer the identifiers by standard tags.

**Comment by tychonievich** [comment]
Discussed 2021-11-30 without resolution. Major points mentioned:

- Extension means fewer SNOTEs, and we know many applications do not handle shared NOTE semantics correctly in 5.5.1
- Standard means more applications keep the IDs
- Standard means 7.0 would allow SNOTE in more places than 7.1 (i.e. SNOTE for shared *or* identifier in 7.0, only for shared in 7.1). This is just a recommendation, not a requirement, so it's not technically against the rules to remove it in a minor release, but I'd rather not do so.

**Comment by tychonievich** [comment]
Discussed 2021-12-07
Many current tools discard extensions they don't understand. Will leave current text; issue closed
